### ISSUE TITLE
Books

### ISSUE THREAD

**Issue by iStudLion** [badbones69/Crazy-Enchantments#127]
When you put a book in /tinkerer it duplicates it (2x)
When you take out the book, they stack and you can do that over and over
Destroy Rates doesnt work

**Comment by kicjow** [comment]
Can you take a screen shot of this happening.

**Comment by iStudLion** [comment]
I will when it happens again!

**Comment by iStudLion** [comment]
![2017-01-02_16 12 34](https://cloud.githubusercontent.com/assets/24688988/21595707/4ba43d58-d107-11e6-95f8-5e3884254cc7.png)
![2017-01-02_16 12 40](https://cloud.githubusercontent.com/assets/24688988/21595703/4b9c17b8-d107-11e6-84ce-18057a29c6c8.png)
![2017-01-02_16 12 45](https://cloud.githubusercontent.com/assets/24688988/21595706/4ba21910-d107-11e6-8e2c-98e36fad1b1e.png)
![2017-01-02_16 12 53](https://cloud.githubusercontent.com/assets/24688988/21595704/4b9edf16-d107-11e6-9677-df4eb6e97e01.png)
![2017-01-02_16 13 00](https://cloud.githubusercontent.com/assets/24688988/21595705/4ba177e4-d107-11e6-92b4-db59beb6da90.png)
![2017-01-02_16 13 03](https://cloud.githubusercontent.com/assets/24688988/21595713/4bd4e5b6-d107-11e6-81df-a59721b34e20.png)
![2017-01-02_16 13 07](https://cloud.githubusercontent.com/assets/24688988/21595708/4bb1736a-d107-11e6-8593-e3ddbf9b1940.png)
![2017-01-02_16 13 10](https://cloud.githubusercontent.com/assets/24688988/21595709/4bb4dec4-d107-11e6-81a9-ded4670846ce.png)
![2017-01-02_16 13 25](https://cloud.githubusercontent.com/assets/24688988/21595710/4bb6b8e8-d107-11e6-9c19-55e15a9ec4f1.png)
![2017-01-02_16 14 44](https://cloud.githubusercontent.com/assets/24688988/21595711/4bbd4460-d107-11e6-8082-8d260c8fbe50.png)
![2017-01-02_16 15 10](https://cloud.githubusercontent.com/assets/24688988/21595712/4bbf3018-d107-11e6-9a2e-a1cc5e3cbeaa.png)
![2017-01-02_16 15 18](https://cloud.githubusercontent.com/assets/24688988/21595714/4bd5a8fc-d107-11e6-945d-0194f74d7038.png)
![2017-01-02_16 15 21](https://cloud.githubusercontent.com/assets/24688988/21595715/4bda4f10-d107-11e6-80a8-f167b163e2ea.png)
![2017-01-02_16 15 27](https://cloud.githubusercontent.com/assets/24688988/21595716/4bdac422-d107-11e6-8506-0602155d3d56.png)
![2017-01-02_16 15 29](https://cloud.githubusercontent.com/assets/24688988/21595717/4bdc4608-d107-11e6-99ff-acfe76adf5c6.png)

Those are screenshots of it duplicating, the first one is in /tinkerer when you click a book to put it tinkerer, nothing happens, when you take it back it starts duping, putting it back dupes, take it back dupe.
The second one is when you open your inventory and click CTRL & Q (to drop whole stack) it duplicated it, 2x and you can do that over and over

**Comment by kicjow** [comment]
Strange, I can't replicate this can you see if it still happens. If so pastebin your enchantments.yml for me
