### ISSUE TITLE
Giving error

### ISSUE THREAD

**Issue by freethemice** [badbones69/Crazy-Enchantments#141]
Sometime when people try and place a book it give this error
http://pastebin.com/R5UpkpPB

**Comment by Yukun99** [comment]
That's not an error with CE, it's somethign else.

**Comment by kicjow** [comment]
Is there anymore to that error?

**Comment by freethemice** [comment]
Yes, Im sorry. I thought I got it all.
http://pastebin.com/ArfR2fzy

**Comment by kicjow** [comment]
Hmmm, that error still doesn't show me anything. Do you know when the error happens?

**Comment by freethemice** [comment]
They where trying to place a book from CE on to a sword. and it won't let them

**Comment by kicjow** [comment]
Could you pastebin your enchantments.yml.

**Comment by freethemice** [comment]
http://pastebin.com/bg1f6QVV

**Comment by kicjow** [comment]
Hmmmm, it would help if the error would show me more. Can you check for a line in the errors for something that says "me.badbones69.BlaBlaBla"

**Comment by freethemice** [comment]
Ok , So I found what cause it 
In the CustomeEnchantments.yml I have a  for the Name Titan:Cyborg
it looks like the colon in the name causes the error.
However in the Enchantments.yml this isn't a problem
I have to have the colon for your plugin to work with my slimefun
can you fix?
