### ISSUE TITLE
Enchantments Error

### ISSUE THREAD

**Issue by EvoBoost** [badbones69/Crazy-Enchantments#144]
Hello again! I'm really bad at config, so that's probably why I'm here again. So, I recently added more lines of description in the Enchantments and Custom Enchantments. I also added 2 new book types and customized the colour of the Enchantments on the items. I think this is the reason why I can't go into anything in the CE list, can't do CE add, remove, and a lot of other stuff. Can you please help me? Thanks!

**Comment by EvoBoost** [comment]
http://pastebin.com/F5vZKFJE - Config
http://pastebin.com/F10nQZCF - Console

**Comment by kicjow** [comment]
Your version is to far out of date. Please update and then check it again.

**Comment by EvoBoost** [comment]
It's still having the same problem

**Comment by kicjow** [comment]
Pastebin the error plz

**Comment by EvoBoost** [comment]
Say on console?

**Comment by kicjow** [comment]
Yes

**Comment by EvoBoost** [comment]
http://pastebin.com/e0KrH0ED

**Comment by kicjow** [comment]
Pastebin your Enchantments.yml

**Comment by EvoBoost** [comment]
http://pastebin.com/ZtNspv3u

**Comment by EvoBoost** [comment]
Find anything wrong?

**Comment by kicjow** [comment]
Strange, there is nothing wrong with that.

**Comment by kicjow** [comment]
Can you send me your new Config.yml

**Comment by EvoBoost** [comment]
Okay

**Comment by EvoBoost** [comment]
http://pastebin.com/cW7PEYLL

**Comment by EvoBoost** [comment]
Anything?

**Comment by EvoBoost** [comment]
...

**Comment by kicjow** [comment]
Sorry about that. Its harder to reply here some times. I compaired your config to the v1.7.5.1 config because thats what the error said you were using. Not sure if you updated but I found you never added some lines. Mainly the transmog scroll options. Try this if your still using v1.7.5.1.
https://hastebin.com/usamiriguv.php

**Comment by EvoBoost** [comment]
I have v1.7.5.2 - would that work?

**Comment by EvoBoost** [comment]
Well, I tried. I can now add enchantments, but I can't click the compass that lists the enchantments.

**Comment by kicjow** [comment]
The problem with the info is because it must not be up to date. Ether compare the file to the default or regenerate the msgs.yml.

**Comment by EvoBoost** [comment]
When I did that, MultiArrow was fixed somehow. Thanks for the help!

**Comment by kicjow** [comment]
Np

**Comment by EvoBoost** [comment]
Wait... It's just MultiArrow 5 that's not working... 1, 2, 3, and 4 work, but not 5

**Comment by kicjow** [comment]
Strange, how do you know its not working?

**Comment by EvoBoost** [comment]
Whenever I try to apply it via command, it says An internal error occurred while attempting to perform this command, then it removes all of the enchantments like I stated before.

**Comment by kicjow** [comment]
Pastebin the error.

**Comment by EvoBoost** [comment]
http://pastebin.com/82vwUfwe

**Comment by EvoBoost** [comment]
Seems to be only when I have other custom enchantments applied. When it's a normal bow and I try to apply it, it works fine.

**Comment by kicjow** [comment]
I am pritty sure that has been fixed in v1.7.6 update. So I recommend updating to the newest version but since ur far behind you will have quite a bit to add to the files.

**Comment by EvoBoost** [comment]
What do I add? I'm a noob at config...

**Comment by kicjow** [comment]
Read the change logs on the main page. You will have to go all the way back to v1.7.5.2 and go from there. Other wise if you just delete ur files and start new then it wouldnt need you to add the lines but you do have to restart

**Comment by EvoBoost** [comment]
I updated it and everything seems to be working fine without me adding/changing anything.

**Comment by EvoBoost** [comment]
Except when I add multiarrow it randomly applies Freeze...
