### ISSUE TITLE
CustomEnchantments Error and gkit 

### ISSUE THREAD

**Issue by ammarmc** [badbones69/Crazy-Enchantments#145]
the bow CustomEnchantments  does not work for 1.8.8
and gkit when i add 2 more  item i get Error when i click twice on the kit 
please add to the
 ArmorOptions
 when i get hit :
      Damaged: or Damager
            PowerIncrease: 0 #How many times the Potion Effects go up each lvl.
            PotionEffects: #Effects that are added to the Damaged.
            - 'BLINDNESS:0, Time:5, Chance:100'

      - 'Item:310, Amount:1, Name:&f&k*&e&l>>&6&lHero Gkit Helmet&e&l<<&f&k*, Enchantments:PROTECTION_ENVIRONMENTAL:4,DURABILITY:3, CustomEnchantments:BurnShield:0-1,Glowing:0-1,Implants:0-5,SmokeBomb:0-3, Lore:&aA special helmet worn by a great hero.,&aTake special care of this.'
      - 'Item:311, Amount:1, Name:&f&k*&e&l>>&6&lHero Gkit Chestplate&e&l<<&f&k*, Enchantments:PROTECTION_ENVIRONMENTAL:4,DURABILITY:3, CustomEnchantments:Freeze:0-5,Savior:0-5,StormCaller:0-5,Cactus:0-3, Lore:&aA special chestplate worn by a great hero.,&aTake special care of this.'
      - 'Item:312, Amount:1, Name:&f&k*&e&l>>&6&lHero Gkit Leggings&e&l<<&f&k*, Enchantments:PROTECTION_ENVIRONMENTAL:4,DURABILITY:3, CustomEnchantments:Freeze:0-5,Fortify:0-5,Molten:0-5,PainGiver:0-5, Lore:&aA special leggings worn by a great hero.,&aTake special care of this.'
      - 'Item:313, Amount:1, Name:&f&k*&e&l>>&6&lHero Gkit Boots&e&l<<&f&k*, Enchantments:PROTECTION_ENVIRONMENTAL:4,DURABILITY:3, CustomEnchantments:Voodoo:1-3,Gears:0-3,Rocket:0-3,AntiGravity:0-3, Lore:&aA special boots worn by a great hero.,&aTake special care of this.'
      - 'Item:261, Amount:1, Name:&f&k*&e&l>>&6&lHero Gkit Bow&e&l<<&f&k*, Enchantments:ARROW_DAMAGE:5,ARROW_FIRE:1,ARROW_INFINITE:1,DURABILITY:3, CustomEnchantments:Piercing:0-5,IceFreeze:0-1,Lightning:0-1,Venom:0-5, Lore:&aA special bow  a great hero.,&aTake special care of this.'
      - 'Item:276, Amount:1, Name:&f&k*&e&l>>&6&lHero Gkit Sword&e&l&f&k*<<, Enchantments:DAMAGE_ALL:5,FIRE_ASPECT:2,LOOT_BONUS_MOBS:3,DURABILITY:3, CustomEnchantments:Vampire:0-5,SlowMo:0-5,Viper:0-5,FastTurn:0-5, Lore:&aA special sword  a great hero.,&aTake special care of this.'

**Comment by ammarmc** [comment]
04:04:42 م [ERROR] Could not pass event InventoryClickEvent to CrazyEnchantments v1.7.5.1
04:04:42 م org.bukkit.event.EventException
04:04:42 م at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.8-R0.1-SNAPSHOT-latest%20(1).jar:git-Spigot-db6de12-18fbb24]
04:04:42 م at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.8-R0.1-SNAPSHOT-latest%20(1).jar:git-Spigot-db6de12-18fbb24]
04:04:42 م at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.8-R0.1-SNAPSHOT-latest%20(1).jar:git-Spigot-db6de12-18fbb24]
04:04:42 م at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.8-R0.1-SNAPSHOT-latest%20(1).jar:git-Spigot-db6de12-18fbb24]
04:04:42 م at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1630) [spigot-1.8.8-R0.1-SNAPSHOT-latest%20(1).jar:git-Spigot-db6de12-18fbb24]
04:04:42 م at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31) [spigot-1.8.8-R0.1-SNAPSHOT-latest%20(1).jar:git-Spigot-db6de12-18fbb24]
04:04:42 م at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9) [spigot-1.8.8-R0.1-SNAPSHOT-latest%20(1).jar:git-Spigot-db6de12-18fbb24]
04:04:42 م at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.8-R0.1-SNAPSHOT-latest%20(1).jar:git-Spigot-db6de12-18fbb24]
04:04:42 م at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
04:04:42 م at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
04:04:42 م at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.8-R0.1-SNAPSHOT-latest%20(1).jar:git-Spigot-db6de12-18fbb24]
04:04:42 م at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot-1.8.8-R0.1-SNAPSHOT-latest%20(1).jar:git-Spigot-db6de12-18fbb24]
04:04:42 م at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8-R0.1-SNAPSHOT-latest%20(1).jar:git-Spigot-db6de12-18fbb24]
04:04:43 م at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8-R0.1-SNAPSHOT-latest%20(1).jar:git-Spigot-db6de12-18fbb24]
04:04:43 م at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8-R0.1-SNAPSHOT-latest%20(1).jar:git-Spigot-db6de12-18fbb24]
04:04:43 م at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
04:04:43 م Caused by: java.lang.NullPointerException
04:04:43 م at me.BadBones69.CrazyEnchantments.API.CrazyEnchantments.getPower(CrazyEnchantments.java:521) ~[?:?]
04:04:43 م at me.BadBones69.CrazyEnchantments.API.CrazyEnchantments.addEnchantment(CrazyEnchantments.java:336) ~[?:?]
04:04:43 م at me.BadBones69.CrazyEnchantments.API.GKitzItem.build(GKitzItem.java:125) ~[?:?]
04:04:43 م at me.BadBones69.CrazyEnchantments.API.GKitz.reloadKits(GKitz.java:244) ~[?:?]
04:04:43 م at me.BadBones69.CrazyEnchantments.API.GKitz.getGKit(GKitz.java:433) ~[?:?]
04:04:43 م at me.BadBones69.CrazyEnchantments.API.GKitz.giveKit(GKitz.java:443) ~[?:?]
04:04:43 م at me.BadBones69.CrazyEnchantments.Controlers.GKitzGUI.onInvClick(GKitzGUI.java:117) ~[?:?]
04:04:43 م at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
04:04:43 م at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
04:04:43 م at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
04:04:43 م at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
04:04:43 م at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.8-R0.1-SNAPSHOT-latest%20(1).jar:git-Spigot-db6de12-18fbb24]
04:04:43 م ... 15 more

**Comment by ammarmc** [comment]
Settings:
  GUI-Size: 27 #Must be a factor of 9.
  Inventory-Name: '&8List of all GKitz'
  GUI-Customization: #This allows you to customize unclickable items into you GUI.
    - 'Slot:1, Item:160:15, Name: '
    - 'Slot:2, Item:160:15, Name: '
    - 'Slot:3, Item:160:15, Name: '
    - 'Slot:4, Item:160:15, Name: '
    - 'Slot:5, Item:160:15, Name: '
    - 'Slot:6, Item:160:15, Name: '
    - 'Slot:7, Item:160:15, Name: '
    - 'Slot:8, Item:160:15, Name: '
    - 'Slot:9, Item:160:15, Name: '
    - 'Slot:10, Item:160:15, Name: '
    - 'Slot:11, Item:160:7, Name: '
    - 'Slot:13, Item:160:7, Name: '
    - 'Slot:15, Item:160:7, Name: '
    - 'Slot:17, Item:160:7, Name: '
    - 'Slot:18, Item:160:15, Name: '
    - 'Slot:19, Item:160:15, Name: '
    - 'Slot:20, Item:160:15, Name: '
    - 'Slot:21, Item:160:15, Name: '
    - 'Slot:22, Item:160:15, Name: '
    - 'Slot:23, Item:160:15, Name: '
    - 'Slot:24, Item:160:15, Name: '
    - 'Slot:25, Item:160:15, Name: '
    - 'Slot:26, Item:160:15, Name: '
    - 'Slot:27, Item:160:15, Name: '
###################################
#             Items: Options
# Item: <ID:MD> - You can choose the item with its id and meta data.
# Amount: <Number> - Choose how many of the item you get.
# Name: <Name> - The display name that goes on the item.
# Lore: <Line 1>,<Line 2>,<Line 3>,<Line 4> - The lore that will go under the enchantments. Split lines with a ','
# Enchantments:<Enchantment>:<Level> - Choose vanilla enchantments here. Split each enchantment with a ','
# CustomEnchantments: <Custom Enchantment>:<Level> - Choose crazy/custom enchantments here. Split enchantments with a ','
# To chose a random level for the crazy/custom enchantments use like this 'CustomEnchantments:<Custom Enchantment>:<Min Level>-<Max Level>'
# Example of this is shows here.
# CustomEnchantments:Overload:1-5,Hulk:1-5 << this will add Hulk and Overload and pick a random level from 1-5 and set it as the power.
###################################
GKitz: #GKit optons.
  Hero: #Name of the GKit.
    Display: #All the display option in the gui.
      Slot: 12 #Slot the item is located at in the gui.
      Item: '160:1' #The item that is displayed for the GKit.
      Glowing: true #Toggle on or off if the item has an enchanted effect.
      Name: '&6&lThe Hero GKit' #Display name of the GKit.
      Lore: #The lore that goes on the display item.
        - '&7A kit that used to be worn'
        - '&7into battle by a great hero.'
        - '&74 CustomEnchantments'
        - '&72 op Enchantments &6(Gears Piercing) '
        - ''
        - '&7Cooldown: &624 Hours'
        - '&7Available in: &6%Day%d, %Hour%h, %Minute%m, %Second%s'
        - '&7&l(&6&l!&7&l) &7Right click to preview'
    Cooldown: '24h' #Cooldown for the GKit. Available options d - Day, h - Hour, m - Minute, s - Second
    Items: #The items that are given the players. 
      - 'Item:310, Amount:1, Name:&f&k*&e&l>>&6&lHero Gkit Helmet&e&l<<&f&k*, Enchantments:PROTECTION_ENVIRONMENTAL:4,DURABILITY:3, CustomEnchantments:BurnShield:0-1,Glowing:0-1,Implants:0-5,SmokeBomb:0-3, Lore:&aA special helmet worn by a great hero.,&aTake special care of this.'
      - 'Item:311, Amount:1, Name:&f&k*&e&l>>&6&lHero Gkit Chestplate&e&l<<&f&k*, Enchantments:PROTECTION_ENVIRONMENTAL:4,DURABILITY:3, CustomEnchantments:Freeze:0-5,Savior:0-5,StormCaller:0-5,Cactus:0-3, Lore:&aA special chestplate worn by a great hero.,&aTake special care of this.'
      - 'Item:312, Amount:1, Name:&f&k*&e&l>>&6&lHero Gkit Leggings&e&l<<&f&k*, Enchantments:PROTECTION_ENVIRONMENTAL:4,DURABILITY:3, CustomEnchantments:Freeze:0-5,Fortify:0-5,Molten:0-5,PainGiver:0-5, Lore:&aA special leggings worn by a great hero.,&aTake special care of this.'
      - 'Item:313, Amount:1, Name:&f&k*&e&l>>&6&lHero Gkit Boots&e&l<<&f&k*, Enchantments:PROTECTION_ENVIRONMENTAL:4,DURABILITY:3, CustomEnchantments:Voodoo:1-3,Gears:0-3,Rocket:0-3,AntiGravity:0-3, Lore:&aA special boots worn by a great hero.,&aTake special care of this.'
      - 'Item:261, Amount:1, Name:&f&k*&e&l>>&6&lHero Gkit Bow&e&l<<&f&k*, Enchantments:ARROW_DAMAGE:5,ARROW_FIRE:1,ARROW_INFINITE:1,DURABILITY:3, CustomEnchantments:Piercing:0-5,IceFreeze:0-1,Lightning:0-1,Venom:0-5, Lore:&aA special bow  a great hero.,&aTake special care of this.'
      - 'Item:276, Amount:1, Name:&f&k*&e&l>>&6&lHero Gkit Sword&e&l&f&k*<<, Enchantments:DAMAGE_ALL:5,FIRE_ASPECT:2,LOOT_BONUS_MOBS:3,DURABILITY:3, CustomEnchantments:Vampire:0-5,SlowMo:0-5,Viper:0-5,FastTurn:0-5, Lore:&aA special sword  a great hero.,&aTake special care of this.'
    Commands: #Is used if you wish to use commands to give other things to players.
    #  - 'ce book overload 5 1 %Player%'
  PeaceKeeper:
    Display:
      Slot: 14
      Item: '160:11'
      Glowing: true
      Name: '&9&lThe Peace Keeper GKit'
      Lore:
        - '&7A kit that used to be worn'
        - '&7into battle by a peace keeper.'
        - '&75 CustomEnchantments'
        - '&71 Soul Enchantments &c(Hulk) &7on the Helmet '
        - '&7and 3 op Enchantments &6(Enlightened Disarmer Gears) '
        - ''
        - '&7Cooldown: &624 Hours'
        - '&7Available in: &6%Day%d, %Hour%h, %Minute%m, %Second%s'
        - '&7&l(&9&l!&7&l) &7Right click to preview'
    Cooldown: '24h'
    Items:
      - 'Item:310, Amount:1, Name:&f&k*&e&l>>&9&lPeace Keeper Gkit Helmet&e&l<<&f&k*, Enchantments:PROTECTION_ENVIRONMENTAL:4,DURABILITY:3, CustomEnchantments:BurnShield:0-1,Hulk:0-2,Glowing:0-1,SelfDestruct:0-5,Mermaid:0-5, Lore:&9A special helmet worn by a peace keeper.,&9Take special care of this.'
      - 'Item:311, Amount:1, Name:&f&k*&e&l>>&9&lPeace Keeper Gkit Chestplate&e&l<<&f&k*, Enchantments:PROTECTION_ENVIRONMENTAL:4,DURABILITY:3, CustomEnchantments:Freeze:0-5,Enlightened:0-5,AcidRain:0-3,Radiant:0-3,Tamer:0-5, Lore:&9A special chestplate worn by a peace keeper.,&9Take special care of this.'
      - 'Item:312, Amount:1, Name:&f&k*&e&l>>&9&lPeace Keeper Gkit Leggings&e&l<<&f&k*, Enchantments:PROTECTION_ENVIRONMENTAL:4,DURABILITY:3, CustomEnchantments:Molten:0-5,Fortify:0-5,Cactus:0-5,Blizzard:0-1, Lore:&9A special leggings worn by a peace keeper.,&9Take special care of this.'
      - 'Item:313, Amount:1, Name:&f&k*&e&l>>&9&lPeace Keeper Gkit Boots&e&l<<&f&k*, Enchantments:PROTECTION_ENVIRONMENTAL:4,DURABILITY:3, CustomEnchantments:Recover:0-1,Voodoo:0-3,Gears:0-3,Rocket:1,AntiGravity:0-3, Lore:&9A special boots worn by a peace keeper.,&9Take special care of this.'
      - 'Item:261, Amount:1, Name:&f&k*&e&l>>&9&lPeace Keeper Gkit Bow&e&l<<&f&k*, Enchantments:ARROW_DAMAGE:5,ARROW_FIRE:1,ARROW_INFINITE:1,DURABILITY:3, CustomEnchantments:Piercing:0-5,IceFreeze:0-1,Lightning:0-1,Boom:0-5,Venom:0-5, Lore:&aA special bow  a peace keeper.,&aTake special care of this.'
      - 'Item:276, Amount:1, Name:&f&k*&e&l>>&9&lPeace Keeper Gkit Sword&e&l<<&f&k*, Enchantments:DAMAGE_ALL:5,FIRE_ASPECT:2,LOOT_BONUS_MOBS:3,DURABILITY:3, CustomEnchantments:Confusion:0-5,Disarmer:0-3,Execute:0-5,Obliterate:0-3,FastTurn:0-5, Lore:&aA special sword  a peace keeper.,&aTake special care of this.'
    Commands:
    #  - 'ce book overload 5 1 %Player%'
  Villain:
    Display:
      Slot: 16
      Item: '160:14'
      Glowing: true
      Name: '&4&lThe Villain GKit'
      Lore:
        - '&7A kit that used to be worn'
        - '&7into battle by a evil villan.'
        - '&75 CustomEnchantments'
        - '&71 Soul Enchantments &c(Guards) &7on the Helmet '
        - '&7and 3 op Enchantments &6(Drunk Overload Rage) '
        - ''
        - '&7Cooldown: &624 Hours'
        - '&7Available in: &6%Day%d, %Hour%h, %Minute%m, %Second%s'
        - '&7&l(&4&l!&7&l) &7Right click to preview'
    Cooldown: '24h'
    Items:
      - 'Item:310, Amount:1, Name:&f&k*&e&l>>&4&lVillan Gkit Helmet&e&l<<&f&k*, Enchantments:PROTECTION_ENVIRONMENTAL:4,DURABILITY:3, CustomEnchantments:Overload:0-5,Guards:0-3,Glowing:0-1,Implants:0-5,PainGiver:0-5, Lore:&cA special helmet worn by a evil villan.,&cTake special care of this.'
      - 'Item:311, Amount:1, Name:&f&k*&e&l>>&4&lVillan Gkit Chestplate&e&l<<&f&k*, Enchantments:PROTECTION_ENVIRONMENTAL:4,DURABILITY:3, CustomEnchantments:Savior:0-5,Insomnia:0-1,Freeze:0-5,Drunk:0-3, Lore:&cA special chestplate worn by a evil villan.,&cTake special care of this.'
      - 'Item:312, Amount:1, Name:&f&k*&e&l>>&4&lVillan Gkit Leggings&e&l<<&f&k*, Enchantments:PROTECTION_ENVIRONMENTAL:4,DURABILITY:3, CustomEnchantments:Voodoo:0-3,Recover:0-1,Cactus:0-3,AcidRain:0-3, Lore:&cA special leggings worn by a evil villan.,&cTake special care of this.'
      - 'Item:313, Amount:1, Name:&f&k*&e&l>>&4&lVillan Gkit Boots&e&l<<&f&k*, Enchantments:PROTECTION_ENVIRONMENTAL:4,DURABILITY:3, CustomEnchantments:SmokeBomb:0-3,Molten:0-5,Fortify:0-5,Rocket:0-3,Anti-Gravity:0-5, Lore:&cA special boots worn by a evil villan.,&cTake special care of this.'
      - 'Item:261, Amount:1, Name:&f&k*&e&l>>&4&lVillan Gkit Bow&e&l<<&f&k*, Enchantments:ARROW_DAMAGE:5,ARROW_FIRE:1,ARROW_INFINITE:1,DURABILITY:3, CustomEnchantments:Piercing:0-5,IceFreeze:0-1,Pull:0-1,Lightning:0-1,Venom:0-5, Lore:&aA special bow  a evil villan.,&aTake special care of this.'
      - 'Item:276, Amount:1, Name:&f&k*&e&l>>&4&lVillan Gkit Sword&e&l<<&f&k*, Enchantments:DAMAGE_ALL:5,FIRE_ASPECT:2,LOOT_BONUS_MOBS:3,DURABILITY:3, CustomEnchantments:Vampire:0-5,Rage:0-5,Trap:0-5,Viper:0-5,Wither:0-5, Lore:&aA special sword  a evil villan.,&aTake special care of this.'
    Commands:
   #   - 'ce book overload 5 1 %Player%'
  PrisonBreak:
    Display:
      Slot: 5
      Item: '160:5'
      Glowing: true
      Name: '&a&lThe PrisonBreak GKit'
      Lore:
        - '&7A kit that used to be worn'
        - '&7into battle by a prisoner.'
        - '&75 CustomEnchantments'
        - '&71 Soul Enchantments &c(Guards) &7on the Helmet '
        - '&7and 3 op Enchantments &6(Drunk Overload Rage) '
        - ''
        - '&7Cooldown: &624 Hours'
        - '&7Available in: &6%Day%d, %Hour%h, %Minute%m, %Second%s'
        - '&7&l(&4&l!&7&l) &7Right click to preview'
    Cooldown: '24h'
    Items:
      - 'Item:310, Amount:1, Name:&f&k*&e&l>>&a&lPrisonBreak Gkit Helmet&e&l<<&f&k*, Enchantments:PROTECTION_ENVIRONMENTAL:4,DURABILITY:3, CustomEnchantments:Overload:0-5,Guards:0-3,Glowing:0-1,Implants:0-5,PainGiver:0-5, Lore:&cA special helmet worn by a evil villan.,&cTake special care of this.'
      - 'Item:311, Amount:1, Name:&f&k*&e&l>>&a&lPrisonBreak Gkit Chestplate&e&l<<&f&k*, Enchantments:PROTECTION_ENVIRONMENTAL:4,DURABILITY:3, CustomEnchantments:Savior:0-5,Insomnia:0-1,Freeze:0-5,Drunk:0-3, Lore:&cA special chestplate worn by a evil villan.,&cTake special care of this.'
      - 'Item:312, Amount:1, Name:&f&k*&e&l>>&a&lPrisonBreak Gkit Leggings&e&l<<&f&k*, Enchantments:PROTECTION_ENVIRONMENTAL:4,DURABILITY:3, CustomEnchantments:Voodoo:0-3,Recover:0-1,Cactus:0-3,AcidRain:0-3, Lore:&cA special leggings worn by a evil villan.,&cTake special care of this.'
      - 'Item:313, Amount:1, Name:&f&k*&e&l>>&a&lPrisonBreak Gkit Boots&e&l<<&f&k*, Enchantments:PROTECTION_ENVIRONMENTAL:4,DURABILITY:3, CustomEnchantments:SmokeBomb:0-3,Molten:0-5,Fortify:0-5,Rocket:0-3,Anti-Gravity:0-5, Lore:&cA special boots worn by a evil villan.,&cTake special care of this.'
      - 'Item:261, Amount:1, Name:&f&k*&e&l>>&a&lPrisonBreak Gkit Bow&e&l<<&f&k*, Enchantments:ARROW_DAMAGE:5,ARROW_FIRE:1,ARROW_INFINITE:1,DURABILITY:3, CustomEnchantments:Piercing:0-5,IceFreeze:0-1,Pull:0-1,Lightning:0-1,Venom:0-5, Lore:&aA special bow  a evil villan.,&aTake special care of this.'
      - 'Item:276, Amount:1, Name:&f&k*&e&l>>&a&lPrisonBreak Gkit Sword&e&l<<&f&k*, Enchantments:DAMAGE_ALL:5,FIRE_ASPECT:2,LOOT_BONUS_MOBS:3,DURABILITY:3, CustomEnchantments:Vampire:0-5,Rage:0-5,Trap:0-5,Viper:0-5,Wither:0-5, Lore:&aA special sword  a evil villan.,&aTake special care of this.'
    Commands:
   #   - 'ce book overload 5 1 %Player%'

**Comment by kicjow** [comment]
Please use pastebin next time. A lot of people are getting that error so I think its a error on my end so Ill look into it.

**Comment by kicjow** [comment]
Please pastebin your config.yml

**Comment by ammarmc** [comment]
hi 
this my config 
and my server ip: PrisonBreak.mcraft.pro
just please fix bow  in CustomEnchantments config the dont work for me when i create
gkit config 
http://pastebin.com/y4qcKJEw      
config         
http://pastebin.com/FUnQ8T35

**Comment by ammarmc** [comment]
my error
 InventoryClickEvent to CrazyEnchantments v1.7.5.2


http://pastebin.com/cDh2E240

**Comment by ammarmc** [comment]
please add BlockList for TransmogScroll
