### ISSUE TITLE
Huge /tinker bug

### ISSUE THREAD

**Issue by ArmonicPvP** [badbones69/Crazy-Enchantments#149]
When players /tinker Recover and take the books out, it gives them 4 books back.

**Comment by kicjow** [comment]
Strange, screen shot what the book that is duping.

**Comment by ArmonicPvP** [comment]
Here is a video: https://youtu.be/HNGzZVYO6hg

No errors are in console.

**Comment by kicjow** [comment]
That isn't happening for me. I even replicated what your book looks like and its not happening. Can you Zip your files and put them in like drop box and send them to me.

**Comment by ArmonicPvP** [comment]
https://www.dropbox.com/s/1rrw4z1nq56m8c3/CrazyEnchantmentsFiles.zip?dl=0

**Comment by ArmonicPvP** [comment]
Did you find the bug?
