### ISSUE TITLE
Transmog scroll doesn't work on CustomEnchantments

### ISSUE THREAD

**Issue by ArmonicPvP** [badbones69/Crazy-Enchantments#154]
The Transmog scroll doesn't work on custom enchantments. Is there a way to fix this? 
Also when adding a Transmog scroll to an item without a name it returns the Bukkit name.

**Comment by kicjow** [comment]
The custom enchantments is working fine for me.
http://prntscr.com/dwjd6x

**Comment by ArmonicPvP** [comment]
It doesn't work for me :( is there a certain thing you put in the customenchantments.yml so they go in order?

**Comment by kicjow** [comment]
No. Did you make sure to add the Rarity option to all of the categories.

**Comment by ArmonicPvP** [comment]
Yes.

**Comment by kicjow** [comment]
Not sure, because its working fine for me.

**Comment by ArmonicPvP** [comment]
That's so odd...
