### ISSUE TITLE
Bug Enchant Telepathy

### ISSUE THREAD

**Issue by BastienCUENOT** [badbones69/Crazy-Enchantments#164]
Hello,
I view a little bug on telepathy enchantment.
When i break a creeper spawner with a pickaxe enchant with telepathy, 2 spawners is given. 1 creeper spawner and 1 pig spawner.
It's normal or it's a bug ?
Thank's

**Comment by kicjow** [comment]
Strange, what CE version do you have. /version crazyenchantments

**Comment by thebastien007** [comment]
1.7.6.3.3

**Comment by thebastien007** [comment]
So ?
