### ISSUE TITLE
No Enchantment Books?

### ISSUE THREAD

**Issue by ghost** [badbones69/Crazy-Enchantments#168]
Everything works fine and good.../ce, everything but the enchants. Whenever I click on the Common, Rare and Legend glass panes, no enchantments come out. Even when I try to do the command it comes with this message 'An internal error occurred while attempting to perform this command.'

Please help?

I don't know what to include etc but I will when you tell me WHAT to include.

**Comment by SilverHuskey** [comment]
Console error report?
