### ISSUE TITLE
/ce not opening

### ISSUE THREAD

**Issue by JokerRaids** [badbones69/Crazy-Enchantments#206]
This is the error that I got when typing /ce.

Severe: null
JavaStackTrace: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.8-R0.1-SNAPSHOT-latest%20(5).jar:git-Spigot-c3c767f-33d5de3]
JavaStackTrace: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.8-R0.1-SNAPSHOT-latest%20(5).jar:git-Spigot-c3c767f-33d5de3]
JavaStackTrace: at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot-1.8-R0.1-SNAPSHOT-latest%20(5).jar:git-Spigot-c3c767f-33d5de3]
JavaStackTrace: at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115) [spigot-1.8-R0.1-SNAPSHOT-latest%20(5).jar:git-Spigot-c3c767f-33d5de3]
JavaStackTrace: at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950) [spigot-1.8-R0.1-SNAPSHOT-latest%20(5).jar:git-Spigot-c3c767f-33d5de3]
JavaStackTrace: at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [spigot-1.8-R0.1-SNAPSHOT-latest%20(5).jar:git-Spigot-c3c767f-33d5de3]
JavaStackTrace: at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53) [spigot-1.8-R0.1-SNAPSHOT-latest%20(5).jar:git-Spigot-c3c767f-33d5de3]
JavaStackTrace: at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot-1.8-R0.1-SNAPSHOT-latest%20(5).jar:git-Spigot-c3c767f-33d5de3]
JavaStackTrace: at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_121]
JavaStackTrace: at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_121]
JavaStackTrace: at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:696) [spigot-1.8-R0.1-SNAPSHOT-latest%20(5).jar:git-Spigot-c3c767f-33d5de3]
JavaStackTrace: at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot-1.8-R0.1-SNAPSHOT-latest%20(5).jar:git-Spigot-c3c767f-33d5de3]
JavaStackTrace: at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot-1.8-R0.1-SNAPSHOT-latest%20(5).jar:git-Spigot-c3c767f-33d5de3]
JavaStackTrace: at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot-1.8-R0.1-SNAPSHOT-latest%20(5).jar:git-Spigot-c3c767f-33d5de3]
JavaStackTrace: at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
JavaStackTrace: at me.badbones69.crazyenchantments.api.currencyapi.CurrencyAPI.getCurrency(CurrencyAPI.java:18) ~[?:?]
JavaStackTrace: at me.badbones69.crazyenchantments.controlers.ShopControler.openGUI(ShopControler.java:49) ~[?:?]
JavaStackTrace: at me.badbones69.crazyenchantments.Main.onCommand(Main.java:194) ~[?:?]
JavaStackTrace: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8-R0.1-SNAPSHOT-latest%20(5).jar:git-Spigot-c3c767f-33d5de3]

**Comment by kicjow** [comment]
Make sure you have essentials or essentialsX when using vault as a currency.
