### ISSUE TITLE
telepathy

### ISSUE THREAD

**Issue by PhanaticD** [badbones69/Crazy-Enchantments#210]
when mining slabs it gives glitched texture item

**Comment by kicjow** [comment]
Strange, I tested and it gave me the slab fine. Could be another plugin messing with it or the servers jar possible. What is your server jar. Do /version in console and paste it here.

**Comment by PhanaticD** [comment]
git-Paper-1104 (MC: 1.11.2)

try with quartz slab

**Comment by kicjow** [comment]
It works fine for me. I am using normal spigot 1.11.2. Maybe the version of paper spigot you have is messing it up or its another plugin doing it.
