### ISSUE TITLE
Unlimited Potion Effects

### ISSUE THREAD

**Issue by JammMusic** [badbones69/Crazy-Enchantments#220]
We have a duel plugin on our Factions server and can't use Custom Enchants on any of the kits. This is because after the game is over, it strips them of their inventory/armor and teleports them back to the main world. Crazy Enchants listens for inventory click events I assume, so it does not register the armor as gone and never removes the effects (even on a relog).

Using the latest version on 1.8.8.

**Comment by kicjow** [comment]
Hmm, not sure what I really could do. You may be able to contact the dev of the duel plugin and have them remove all potion effects when it ends and it should fix that.
