### ISSUE TITLE
Furnace / Autosmelt Nit Working

### ISSUE THREAD

**Issue by TheKillHDmc** [badbones69/Crazy-Enchantments#223]
Hello,

The enchant furnace and autosmelt doesn't works on my op prison server ( pickaxe )

My players need a permisison to use it ?

Thanks !

**Comment by kicjow** [comment]
Strange, there is no permission needed. Maybe it is another plugin stopping mine from doing it. I am not sure if you have any other plugin that may edit block drops but if you do try disabling the plugin and seeing if it starts to work.
