### ISSUE TITLE
Help With The Gkitz.yml Folder (Editing It)

### ISSUE THREAD

**Issue by KfwPlayz** [badbones69/Crazy-Enchantments#224]
So the version I am using is 1.8.9 for my server in development, I am trying to add things to the gkits like a sword and axe to Hero kit a sword and Villain an axe and I'm also changing the custom enchants in the kits. Could someone please look at the folder and see what I did wrong? The plugin stops working when I add it back in the server once I was done editing it.
[GKitz.txt](https://github.com/kicjow/Crazy-Enchantments/files/1150800/GKitz.txt)

**Comment by kicjow** [comment]
Not sure what happened when you were editing but there was stuff all over the place and so it broke the format. Here is the fixed version. Also, make sure next time to pastebin the error/file and not send a file ;)
https://pastebin.com/0p0e0PFL

**Comment by KfwPlayz** [comment]
Is it because I used normal Notepad at first and not Notepad++?


On Monday, July 17, 2017, 2:51:35 AM EDT, BadBones69 <notifications@github.com> wrote:


Not sure what happened when you were editing but there was stuff all over the place and so it broke the format. Here is the fixed version. Also, make sure next time to pastebin the error/file and not send a file ;)
https://pastebin.com/0p0e0PFL

**Comment by kicjow** [comment]
Ya, that is probably why it was messed up. If it fixes the issue make sure to close this issue so I know its fixed ;)

**Comment by KfwPlayz** [comment]
No it didn't work, it did the exact same thing it did before, I am running it on a 1.8.8 server with the latest ce version, could that cause a problem?

On Monday, July 17, 2017, 3:42:56 PM EDT, BadBones69 <notifications@github.com> wrote:


Ya, that is probably why it was messed up. If it fixes the issue make sure to close this issue so I know its fixed ;)

**Comment by kicjow** [comment]
No, my plugin supports 1.8.8 fine. Did you copy and paste all of the lines from that pastebin into your gkit file. Make sure it over writes what you currently have.

**Comment by KfwPlayz** [comment]
Yes I did but it didn't copy right i think idk, it seemed good though

On Monday, July 17, 2017, 10:52:33 PM EDT, BadBones69 <notifications@github.com> wrote:


No, my plugin supports 1.8.8 fine. Did you copy and paste all of the lines from that pastebin into your gkit file. Make sure it over writes what you currently have.

**Comment by kicjow** [comment]
So is it working fine now?

**Comment by KfwPlayz** [comment]
No I can't edit it or it breaks the entire plugin, i'm gonna try re-editing it from scratch, like adding the stuff i  wanted back

On Thursday, July 20, 2017, 4:46:45 PM EDT, BadBones69 <notifications@github.com> wrote:


So is it working fine now?

**Comment by kicjow** [comment]
Alright
