### ISSUE TITLE
Milk removes negative potion effects - They don't come back

### ISSUE THREAD

**Issue by Dakotaa** [badbones69/Crazy-Enchantments#225]
Hello, I'm still having a major issue with this plugin. Players on my server are able to get items with custom enchants to use in PvP. One item, for example, uses the Insomnia enchantment. Normally, the negative effects of this enchantment make it balanced, but due to a bug with the plugin, players are able to drink a bucket of milk and remove the potion effects from the enchantment, while keeping the high chance of double damage. Paired with an axe with the Rekt enchantment, they are able to deal insanely high damage in PvP, which can result in 1-2 hitting a player in full protection 4 armour, due to this bug.

I hope a fix for this is possible, as players have invested a lot of ingame money into items with these enchantments, but I can't see us keeping the plugin if it continues to break PvP.

**Comment by kicjow** [comment]
Thanks, ill make sure to fix that so that it updates their potion effects.
