### ISSUE TITLE
Enchantment Tables - Unusable

### ISSUE THREAD

**Issue by ghost** [badbones69/Crazy-Enchantments#227]
Hello,

I'm using the latest version 1.7.9.2.4 with the latest Spigot 1.12 jar.

I have an issue with Enchantment Tables not working (vanilla style).
I had tested and removed every plugin possible and it never occurred to me that this plugin would be the cause (since I never had trouble with this plugin in the past)

Here is a link to my post regarding this issue for a preview of what the problem is, it seems like a inventory click event getting canceled: https://www.spigotmc.org/threads/spigot-1-12-enchantment-table-not-working.256730/

I was looking around the config for some sort of enchantment table option but couldn't find one relative to the problem.

Please help, thanks!

**Comment by kicjow** [comment]
Strange, I can't seems to replicate it. Try setting this option to false.
https://github.com/kicjow/Crazy-Enchantments/blob/master/config.yml#L249
If you don't see that option then add it in and set it to false.

If that doesn't fix it then pastebin the config and send the link.
