### ISSUE TITLE
Custom enchant potions not working

### ISSUE THREAD

**Issue by ehcrafter** [badbones69/Crazy-Enchantments#228]
so i made a custom enchant and saved it. but when i used it ingame it gave me the wrong potion effects

  Tank: #Enchantment
    Enabled: True #Enable and disable the enchantment
    Name: 'Tank' #The in-game name of the enchantment
    Color: '&4' #The color of the enchantment on the item
    BookColor: '&4&l' #The color of the enchantment on the book
    MaxPower: 5 #Max lvl the enchantment goes up to
    Categories: #All the categories the Enchantment can be found in
      - 'Legendary'
    Info:
      Name: '&4&lTank'
      Description:
        - '&c&lArmor Only'
        - '&3Gives You Mining Fatgiue, Strength'
        - '&3And High Resistance'
    EnchantOptions: #Customizing Options for each enchantment.
      ItemsEnchantable: 'Armor' #You can pick from Armor, Boots, Helmet, Axe, Sword, Weapons(Swords & Axes), and Bow.
      ArmorOptions: #Options that only effect Armor Enchantments.
        PowerIncrease: 0 #How many times the Potion Effects go up each lvl.
        PotionEffects: #Potion types that will be applied.
          - 'MINING_FATIGUE:1, Time:1000000'
          - 'INCREASE_DAMAGE:3, Time:1000000'
          - 'RESISTANCE:10, Time:1000000'

and the effects i got were these
https://gyazo.com/5b42d19e70cfb29e52d52808fd2403be

**Comment by kicjow** [comment]
Try DAMAGE_RESISTANCE and SLOW_DIGGING.
They can be found here:
https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/potion/PotionEffectType.html
