### ISSUE TITLE
This plugin doesn't work on 1.12 minecraft

### ISSUE THREAD

**Issue by 2BTube** [badbones69/Crazy-Enchantments#235]
Ok I am just gonna make this simple, here's the issue... normally when you drag the book into the item, the book breaks and the enchantment goes into the item right ? Well... If u're using **1.12**, They will do the opposite... The Item breaks and the book is still there. :(

Pls Fix This bug with **1.12** minecraft version cause this is very disappointing as i am using this plugin on a **1,12** server...

Oh yeah, and u said that the "tested minecraft versions : 1.7, 1.8, 1.9, 1.10, 1.11, **1.12**"
That means 1.12 should work cause you've tested it but it's not :(

**Comment by kicjow** [comment]
Hello, I don't want to sound rude but how you explained this made it sound like I didn't test the features and stuff but I have and I just tested this report and my plugin is working fine in 1.12. I was able to put a book onto an item and it removed the book and added the enchantment. Could you check the console to see if there are any errors? Also if it keeps happening can you record a video of it and send me a link to the video.

**Comment by 2BTube** [comment]
Ok, i will do it tomorrow and thx btw for the quick reply !!

**Comment by 2BTube** [comment]
I've gave u the video and the config

**Comment by kicjow** [comment]
I can't seem to replicate it. I think this may be a visual glitch on ur client side.

**Comment by Philokrates** [comment]
This same thing happens to me in 1.12. I cant put any of the enchantments or items on any tool or armor piece because it just deletes the item. I reloaded the plugin but it didn't work. I even fully deleted it and re-downloaded it but it didn't work either

**Comment by kicjow** [comment]
Try Updating to 1.12.1 and see if it still does it.

**Comment by WindUnwaken** [comment]
I also have  similar issue on 1.12 ,but it only happens when player fast-click on item .

**Comment by kicjow** [comment]
Weird, I still can't seem to replicate it. I am using this version of spigot and its working just fine for me.

CraftBukkit version git-Spigot-65e8124-357b573 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)

**Comment by kicjow** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [https://github.com/kicjow/Crazy-Enchantments/issues/235](https://trello.com/c/x3nseONw/1-https-githubcom-kicjow-crazy-enchantments-issues-235)

**Comment by 2BTube** [comment]
Sad that it still broken for me :( it has been months...
Can u find a way to fix this ? i'll donate to you if u succeed :/

**Comment by Castiella** [comment]
Sorry to comment on a dead topic but i am also having this issue. It sometimes applies, sometimes breaks the item.
