### ISSUE TITLE
Doesnt work on 1.12

### ISSUE THREAD

**Issue by Philokrates** [badbones69/Crazy-Enchantments#246]
Every time I try to put and enchantment on an item it breaks it. White & Black scrolls break the items as well. I reloaded to config. & that didn't work. I even fully deleted the plugin and reinstalled it and but it still didn't work. The only way I can put the enchantment on the item is by using commands, but that takes out the risk factor.

**Comment by kicjow** [comment]
Strange, are there any errors in the console. Also, can do you /version and send me what it says.

**Comment by Philokrates** [comment]
"This server is running CraftBukkit version git-Spigot-65e8124-357b573 (MC:1.12.1) (Implimenting API version 1.12.1-R0.1-SNAPSHOT)
Checking version, please wait...
You are running the latest version"
I havent noticed any errors

**Comment by kicjow** [comment]
Strange, it works fine for me. It could be another plugin doing it but I am not sure. Could you show me a video or Gif of it so I can see what is happening.
