### ISSUE TITLE
Necromancer

### ISSUE THREAD

**Issue by WindUnwaken** [badbones69/Crazy-Enchantments#249]
Looks like doesn't work on 1.12.

But Infestation and Guards works well

**Comment by kicjow** [comment]
Can you please explain what doesn't work. They don't spawn or what?

**Comment by WindUnwaken** [comment]
It doesn't spawn

**Comment by WindUnwaken** [comment]
Others health bug with video
https://www.youtube.com/watch?v=X5Mh51u8_Oc&feature=youtu.be

**Comment by kicjow** [comment]
1. Sounds like another plugin stopping the mobs from spawning. Because it's working fine on my server.

2. Strange, I just tested and its working fine for me. I had overload and opened a chest and it was fine. Could be another plugin doing that also. What version of CE do you have?

**Comment by TheDeviantCrafter** [comment]
I've been testing this myself. It works for PvP, but not in PvP. If you expect to use these against mobs, Infestation will not trigger.

Oddly enough, Guards does.
