### ISSUE TITLE
Rage break on damage API

### ISSUE THREAD

**Issue by DorCoMaNdO** [badbones69/Crazy-Enchantments#254]
An event when a player takes damage with "Rage break on damage" enabled when they have their Rage building up would be nice to have, with an option to cancel to maintain the rage multiplier, this would allow plugins to make the rage break chance based or only affect PvP as opposed to PvE.

**Comment by kicjow** [comment]
I may add this if I get the chance. Not totally sure why this would be needed but I may get around to adding it.

**Comment by DorCoMaNdO** [comment]
There's a server with a bunch of dungeons made for 3 players, each player gets a different kit, there's a "Damage" kit which is based around the Rage enchantment, but due to the large mob count in the dungeon Rage is useless since it is broken with every hit. The reason the "Rage break on damage" setting isn't disabled is because players do like the change in PvP, but they would also like Rage to be useful in PvE (or at least the dungeons), hence the request to be able to alter the behavior.
