### ISSUE TITLE
Making Custom Enchants has an issue.

### ISSUE THREAD

**Issue by xxJinxedxx** [badbones69/Crazy-Enchantments#257]
@kicjow ,i made a simple custom enchant "Insomnia", which was already in the plugin but for armors.
The setup is right and all the names have been changed or redone in so that the plugin would not get confused.., it just gives out an error on entity damage with the enchantment.
https://hastebin.com/ahufanemey.vbs

**The Original Insomnia in Enchantments.yml**
https://hastebin.com/wevokuqota.php

**My custom made Insomnia in CustomEnchantments.yml**
https://hastebin.com/lozabukogu.php

_P.S. - I  have tried to change the name and the "SLOW" to "SLOWNESS" but it has no effect.
Thanks!_

**Plugin Version**
Crazy Enchantments[v1.7.9.3.2]
**Server Version**
[Server] INFO This server is running CraftBukkit version git-PaperSpigot-"8b18730" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**Comment by Jnxd1** [comment]
**Update**
Tried to make few more custom enchantments, but it seems that it is not working right.
It keeps out giving me that error and the enchantments/potion effects are not working/applying right.
