### ISSUE TITLE
Most enchantments don't work in PvP

### ISSUE THREAD

**Issue by TheDeviantCrafter** [badbones69/Crazy-Enchantments#258]
For PvP-heavy servers, this plugin works great, but for PvE it starts to have some problems. There's a pretty long list of custom enchantments that work against players, but not mobs. This can be confusing to players, and makes the bulk of the enchantments useless on servers without a heavy PvP scene.

I've done some rough testing, and here's a list of the ones I found that seem to be limited to PvP. Note that I may have gotten one or two wrong:

- Blizzard

- Dizzy
- Cursed
- Acid Rain
- Voodoo
- Recover
- Pralyze
- Skillswype
- Snare
- Freeze
- Fortify
- Molten
- Paingiver
- Trap
- Wither
- Sandstorm
- Radiant
- Intimidate
- Doctor
- Infestation
- Decapitate (possibly - needs more testing)
- Confusion
- Disarmer
- Execute
- Headless (possibly - needs more testing)
- Necromancer
- Venom
- Slomo
- Blindness
- Viper
- Stormcaller
- Leadership
- Piercing (possibly - needs more testing)

A few of these would need special handling. For example, Headless and Decapitation would need to drop wither skeleton heads and other mob heads, and would probably need a config setting since that can mess with balance (charged creepers exist). Skillswype could pull free XP from mobs on hit, but only work on a mob a few times, maybe giving as much XP as you'd expect to get from killing it.

Recover should also get a config setting deciding if it should only work on players, bosses, all mobs, or a combination of those three.

**Comment by hitmanov** [comment]
I comprehend where Blizzard is endeavoring to run what with attempting to make PvP unmistakably adjusted. Anyway Blizzard has a past filled with being to a great degree foolhardy so I'd jump at the chance to specify a couple of issues that I think can come up.
