### ISSUE TITLE
The Blast enchantment is incompatible with silk touch

### ISSUE THREAD

**Issue by TheDeviantCrafter** [badbones69/Crazy-Enchantments#264]
When using a pickaxe with Blast and Silk Touch, mining smooth stone will drop cobblestone. It does seem to work with Fortune, though.

**Comment by razorrider7** [comment]
Yeah, I've noticed that only the block you mine gets Fortuned or the Silk Touched. Also, Glowing redstone ore isn't enabled by default for Blast, so I had to go in and add the block id 74 to the BlockList.yml file.
