### ISSUE TITLE
God Mode Bug

### ISSUE THREAD

**Issue by nhulston** [badbones69/Crazy-Enchantments#298]
"So
to do it, all you need is a Ce that gives Resistance.
And
Put the Ce on a chestplate and equip it.
Put a normal chestplate in your 3rd inven slot.
Press Q and 3. it will unequip your Ce one and replace it with the normal one
But you will keep your resistance
But since vanilla can't handle it. it gives you godmode.
So I recommend disabling all Ce's that hand out damage resistance"

A player told me this, it actually worked.

**Comment by pinchcraft** [comment]
So pretty much just platemail
