### ISSUE TITLE
Unbreaking 5?

### ISSUE THREAD

**Issue by jimmybenoit** [badbones69/Crazy-Enchantments#299]
I could probably find this somewhere else but on this server i play on this player somehow got a unbreaking 5 pickaxe after a staff member left and claim its a feature of crazy enchants i tried opening like 2 inventories of legendary books and not one of them was unbreaking 5 is this some staff abuse or is it a feature.
Probably the wrong spot but idc

**Comment by CollinHerber** [comment]
It was likely something they did custom on the server. Unbreaking V does not come out of the box on crazy enchantments, however you can change names of things and make your own custom enchantments that can behave as such.

My guess is they weren't lying, however they were custom coded.

Hope this helps!

**Comment by jimmybenoit** [comment]
Just got an email notification for this 1 1/2 years later
