### ISSUE TITLE
Problem with enchantment "Experience"

### ISSUE THREAD

**Issue by jlopez994** [badbones69/Crazy-Enchantments#301]
Hi, I'm not sure if this is a real issue but I think it is relevant.

The problem is this enchantment is working a "bit too well". I explain, even if you already mined the block, you can place it down and mine it again. The enchantment will trigger and give you experience again.

Thanks in advance.

**Comment by CollinHerber** [comment]
Which enchantment are we talking about here?

**Comment by esejuli94** [comment]
Experience enchantment
