### ISSUE TITLE
Error when doing /ce

### ISSUE THREAD

**Issue by Shawn11564** [badbones69/Crazy-Enchantments#305]
05.02 13:11:02 [Server] INFO MrShawn issued server command: /ce
05.02 13:11:02 [Server] ERROR null
05.02 13:11:02 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'ce' in plugin CrazyEnchantments v1.7.9.3.7
05.02 13:11:02 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.8.8-latest.jar:git-Spigot-21fe707-e1ebe52]
05.02 13:11:02 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.8.8-latest.jar:git-Spigot-21fe707-e1ebe52]
05.02 13:11:02 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot-1.8.8-latest.jar:git-Spigot-21fe707-e1ebe52]
05.02 13:11:02 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot-1.8.8-latest.jar:git-Spigot-21fe707-e1ebe52]
05.02 13:11:02 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot-1.8.8-latest.jar:git-Spigot-21fe707-e1ebe52]
05.02 13:11:02 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.8.8-latest.jar:git-Spigot-21fe707-e1ebe52]
05.02 13:11:02 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.8.8-latest.jar:git-Spigot-21fe707-e1ebe52]
05.02 13:11:02 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.8-latest.jar:git-Spigot-21fe707-e1ebe52]
05.02 13:11:02 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
05.02 13:11:02 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
05.02 13:11:02 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.8-latest.jar:git-Spigot-21fe707-e1ebe52]
05.02 13:11:02 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot-1.8.8-latest.jar:git-Spigot-21fe707-e1ebe52]
05.02 13:11:02 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8-latest.jar:git-Spigot-21fe707-e1ebe52]
05.02 13:11:02 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8-latest.jar:git-Spigot-21fe707-e1ebe52]
05.02 13:11:02 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8-latest.jar:git-Spigot-21fe707-e1ebe52]
05.02 13:11:02 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
05.02 13:11:02 [Server] INFO Caused by: java.lang.ArrayIndexOutOfBoundsException

**Comment by Shawn11564** [comment]
This is my config.yml file: https://pastebin.com/ekM06vr8

**Comment by kicjow** [comment]
Seems it could be from this option being set to false instead of a number.
http://take.ms/c49JG
