### ISSUE TITLE
Custom Enchants disappear off of armour

### ISSUE THREAD

**Issue by SpiritFireGaming** [badbones69/Crazy-Enchantments#306]
Whenever I put on armour with custom enchants, it removes the custom enchants and leaves it just a vanilla armour piece.

**Comment by kicjow** [comment]
Strange, it might maybe from another plugin. I have heard from another user this happening and it turned out to be another plugin. Though they didn't tell me what plugin it was.

**Comment by BluGhostYT** [comment]
@kicjow , this issue needs to be closed as I have provided the plugin that was causing the issue.
