### ISSUE TITLE
Duels

### ISSUE THREAD

**Issue by ItsAlpal** [badbones69/Crazy-Enchantments#329]
Dear @kicjow ,
I have [this ](https://www.spigotmc.org/resources/duels.20171/)duel plugin on my server. The kits they have to choose from all have Glowing on the helmets and various other enchantments. When a player selects a kit, the plugin automatically equips their armour and teleports them.
The issue is that they do not get the effects. They have to take the armour off and then place it back to get them. Is there any way around this?
Thanks in advance.

**Comment by ItsAlpal** [comment]
pls? bumb

**Comment by realchessx** [comment]
Crazy enchantment don't support duel plugin.
