### ISSUE TITLE
menu problems

### ISSUE THREAD

**Issue by vicehound** [badbones69/Crazy-Enchantments#340]
Howdy! I love the idea of the enchantments and really look foward to using them but in the 'menus' you have everything just seems to appear as a stone block. Is there a fix to this? I thought it was my resource pack at first but the problem persisted through the default texture pack

**Comment by Vestle** [comment]
This has to do with the old 1.12 MC IDs being in the configs. But when updated to the new names, the gui will let players take the items out. So we need a 1.13.1 update
