### ISSUE TITLE
No permission for /ce

### ISSUE THREAD

**Issue by Zenya4** [badbones69/Crazy-Enchantments#353]
Title says it all. When I modify the items inside the config, players no longer have permission to use th ce GUI. Yes, they do have the permission node `crazyenchantments.access`. But even with that they still can't open the GUI and it gives a no-permission error message. Attached is the config I'm using: https://pastebin.com/hNmXhFGY
![screen shot 2018-12-16 at 10 30 52 pm](https://user-images.githubusercontent.com/15248687/50055020-2768c800-0184-11e9-8cf2-afcc4d3f6c6e.jpg)

**Comment by TurboPhantom** [comment]
I also have this issue just happened to me

**Comment by Zenya4** [comment]
Unfortunately I don’t think it will ever be fixed because the dev is inactive. A way to bypass this is to give players `crazyenchantments.*` and negate the other administrator nodes accordingly. However, that is rather inadvisible as it would be dangerous if you missed something out so only do it if you’re desperate.

**Comment by TurboPhantom** [comment]
how do you negate a node?

**Comment by Zenya4** [comment]
Depends on the permissions plugin you use. Most major permissions plugins support negating nodes. Check their wiki.

**Comment by AIMOREwastaken** [comment]
How would I fix this with luck perms
