### ISSUE TITLE
Damaging players gives GriefPrevention Error

### ISSUE THREAD

**Issue by Disorbs** [badbones69/Crazy-Enchantments#356]
So anytime i attack players it triggers an error which im guessing its related to GP support

Latest: CE Dev
Latest: GP
Server: 1.13.2 Paper

Error - https://hastebin.com/sixakekefi.cs

**Comment by pmme** [comment]
If you can clone the repo and build it yourself, that error is fixed here: https://github.com/kicjow/Crazy-Enchantments/pull/358
