### ISSUE TITLE
Remove SimpleClans Dependency

### ISSUE THREAD

**Issue by TheMonDon** [badbones69/Crazy-Enchantments#376]
<dependency>
            <groupId>net.sacredlabyrinth.phaed.simpleclans</groupId>
            <artifactId>SimpleClans</artifactId>
            <version>2.7.11</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/src/main/library/SimpleClans.jar</systemPath>
        </dependency>

Remove this as the plugin is dead and unable to be downloaded or built from github.

**Comment by badbones69** [comment]
Thanks
