### ISSUE TITLE
CrazyEnchantments v1.8Dev-Build-V4 - crazyenchantments.access not giving /ce

### ISSUE THREAD

**Issue by Roselynnn** [badbones69/Crazy-Enchantments#384]
Currently using the latest Dev Build on Spigot 1.14, which is functioning as-normal except for /ce. Players are given crazyenchantments.access but it will give them "You do not have permission to use that command!" upon execution. crazyenchantments.blacksmith and crazyenchantments.tinker work flawlessly, and players are able to open and use both guis without issue.
![image](https://user-images.githubusercontent.com/28676457/57644226-e29d5d80-7578-11e9-8588-5eb557f971c0.png)
![image](https://i.gyazo.com/0786d63ec9ecd2b1e930da06b4464029.gif)
I'm not the first to experience this issue either, but since the dev has become active again I think i'll receive a more helpful response than the author of the previous thread.
[https://github.com/badbones69/Crazy-Enchantments/issues/353](url)
![image](https://user-images.githubusercontent.com/28676457/57644487-6fe0b200-7579-11e9-8a7e-dc3e2c57a0eb.png)
**Config.yml** https://pastebin.com/jQtvwVee

**Comment by VersionOmega** [comment]
I'm also experiencing this, hope this get's solved <3

**Comment by VersionOmega** [comment]
Use crazyenchantments.gui

**Comment by badbones69** [comment]
^^
