### ISSUE TITLE
 CrazyEnchantments v1.8-Dev-Build-v4 not up to date?

### ISSUE THREAD

**Issue by samidont0817** [badbones69/Crazy-Enchantments#386]
07.06 19:27:35 [Server] ERROR Error occurred while enabling CrazyEnchantments v1.8-Dev-Build-v4 (Is it up to date?)
07.06 19:27:35 [Server] INFO java.lang.NoSuchMethodError: uk.antiperson.stackmob.api.EntityManager.<init>(Luk/antiperson/stackmob/StackMob;)V
07.06 19:27:35 [Server] INFO at me.badbones69.crazyenchantments.multisupport.StackMobSupport.<clinit>(StackMobSupport.java:11) ~[?:?]
07.06 19:27:35 [Server] INFO at me.badbones69.crazyenchantments.Main.onEnable(Main.java:94) ~[?:?]
07.06 19:27:35 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[minecraft_server.jar:git-Paper-564]
07.06 19:27:35 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:326) ~[minecraft_server.jar:git-Paper-564]
07.06 19:27:35 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:406) ~[minecraft_server.jar:git-Paper-564]
07.06 19:27:35 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443) ~[minecraft_server.jar:git-Paper-564]
07.06 19:27:35 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357) ~[minecraft_server.jar:git-Paper-564]
07.06 19:27:35 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608) ~[minecraft_server.jar:git-Paper-564]
07.06 19:27:35 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570) ~[minecraft_server.jar:git-Paper-564]
07.06 19:27:35 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431) ~[minecraft_server.jar:git-Paper-564]
07.06 19:27:35 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[minecraft_server.jar:git-Paper-564]
07.06 19:27:35 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:786) ~[minecraft_server.jar:git-Paper-564]
07.06 19:27:35 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
07.06 19:27:35 [Server] INFO [CrazyEnchantments] Disabling CrazyEnchantments v1.8-Dev-Build-v4

**Comment by badbones69** [comment]
Which mob stack plugin do you use?

**Comment by samidont0817** [comment]
StackMob 3 and I will look to see if it's up to date.

**Comment by badbones69** [comment]
Alright and try on the newest dev build.

**Comment by samidont0817** [comment]
Still does not work.

**Comment by badbones69** [comment]
This plugin correct?
https://www.spigotmc.org/resources/stackmob-enhance-your-servers-performance.29999/

Can you pastebin the new error from the current dev build.

**Comment by samidont0817** [comment]
Yes that is the correct plugin. And here is the new error.
https://pastebin.com/dXMUjCs0

**Comment by badbones69** [comment]
Strange, it loaded and hooked fine for me. My guess your MobStacker isn't the right one or something. Delete the MobStacker jar then replace it with a newly downloaded one from the Spigot page.

**Comment by samidont0817** [comment]
So I have replaced both CE and StackMob with the most recent versions and it still does not work. I do not know if this is the same error as before. but here is the pastebin https://pastebin.com/cThbw3JK

**Comment by badbones69** [comment]
Can you pastebin ur startup log for me? I had it load just fine on Spigot 1.13.2 using v4.0.2.

My Log: https://pastebin.com/2qqK7JTe

**Comment by samidont0817** [comment]
https://pastebin.com/04iA2bTc
There's the startup log~

**Comment by badbones69** [comment]
Something very strange is going on on ur server it seems. I see StackMob plugin loaded fine but then Mine and MyPet plugin can't seem to hook even though on my server it's fine. It seems there is a Paper Spigot update for ur server so I recommend updating that then see if it fixes it.

**Comment by samidont0817** [comment]
I updated it to v6 and it seems to all work :D

**Comment by badbones69** [comment]
Alright unsure what was happening.
