### ISSUE TITLE
When an enchantment has a purple (&5) name, it's not registered as an enchantment.

### ISSUE THREAD

**Issue by VersionOmega** [badbones69/Crazy-Enchantments#387]
So the lore by default in Minecraft is &5 and italic and I think that when giving an enchantment the colour &5, Minecraft sees it as regular lore and not an enchantment and so it italicises it.

See here:

https://cdn.discordapp.com/attachments/196107873397374976/587981609836478504/Untitled.png

If you count the enchantments (discluding the purple ones at the bottom), you get 29 which is what the transmog scroll reads. The purple enchantments should have a rarity of 4 which would put them above the blue ones which have a rarity of 3 but since they have been put at the bottom, it shows that Minecraft sees it as regular lore and not the lore of the enchantments. Because of this, not only does the transmog scroll not register it, but the plugin doesn't either meaning it doesn't act as an enchantment (i.e Ninja doesn't give it's specific potion effects).

Hope I did well in explaining this issue :3

**Comment by badbones69** [comment]
Could you post a new picture from something like imgur?

**Comment by VersionOmega** [comment]
My bad, https://imgur.com/a/wH9FQC5

**Comment by Niko302** [comment]
same with &f, it breaks the whole plugin
