### ISSUE TITLE
Trying to stack Guards, Tamer, necromancer, and Infestation

### ISSUE THREAD

**Issue by Zephrius** [badbones69/Crazy-Enchantments#392]
So I am trying to make like a "summon master" armor that when triggered it summons all four but it seems to only prioritize the first enchantment. Is there something in the config I need to change? Or is this a bug or is it just not supposed to work this way. Also if it is not supposed to, is there I can make it work that way?

**Comment by badbones69** [comment]
It is currently coded that only 1 type of ally type enchantment where it spawns mobs to fight for you will work at a time. I will look into allowing all of them to work at the same time but unsure when will be unlocked.

**Comment by Zephrius** [comment]
Thank you for getting back to me, and I hope it gets added eventually. I
recommend, if possible, to make it a configurable option. Thank you again.
