### ISSUE TITLE
The enchanted book disappeared because the backpack was full.

### ISSUE THREAD

**Issue by zonamychina** [badbones69/Crazy-Enchantments#400]
Vulnerabilities Step: First enchant the CE Enchanting Book on the item, fill the backpack after enchantment, then open /CE to buy the black ink bag, click the black ink bag in the backpack to remove the enchantment of the item, provided that the backpack is still full and there is no vacancy, then remove the enchantment attribute in the item with the black ink bag, and you will find that the enchantment book of the item is not in the backpack, because the backpack is full, and the enchantment effect of the item has disappeared, please ask the author to repair this BUG test plug-in: [1.7.9.4]

**Comment by badbones69** [comment]
Fixed: 6c163ba9718a5920c029a858a15b8cd9f02eaca0
