### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by AccioAce** [badbones69/Crazy-Enchantments#402]
Hello,

CrazyEnchant Dev Build v6 has a console error: https://gyazo.com/4eefb2d4875c16188f527eaebbeefa23

**Comment by badbones69** [comment]
Can you pastebin the log file for me as that isn't the full error.

**Comment by AccioAce** [comment]
Yeah here: https://pastebin.com/T3Aq9h6M

**Comment by badbones69** [comment]
I am unsure why it is erroring. Do you know what block the Blast enchantment is breaking? If not sure make sure Air is not in ur BlockList file.

**Comment by AccioAce** [comment]
I'm not sure but I can check and I also want to report this as well, I notice some enchantments doesn't work as the players reported it to me but most works.

**Comment by badbones69** [comment]
Can you make a new issue with the enchantments that do not work.

**Comment by AccioAce** [comment]
Yeah I can try too.

**Comment by badbones69** [comment]
Did you find the block causing the issue or check if air may have been in the block list?

**Comment by AccioAce** [comment]
I just checked, it seems like "air" is not on the block list.

**Comment by badbones69** [comment]
Can you pastebin the file for me.

**Comment by AccioAce** [comment]
Here is a pastebin: https://pastebin.com/4twmbzuB

**Comment by badbones69** [comment]
Alright, strange I couldn't find an issue but the next update should fix the error in cosnole.
f6e121eede20fce92fa45c5f422c8dc3e67cafff

**Comment by AccioAce** [comment]
Hello badbone, 

I'm only reopening this to make sure is fixed and solved. Recent update: v1.8 Dev Build v6.1 was it suppose meant to fix it? If so, the console spam is still there.

- Thanks

**Comment by badbones69** [comment]
It has not yet been posted. The update should be out soon though.

**Comment by AccioAce** [comment]
Alright thanks
