### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by JoeTornadoz** [badbones69/Crazy-Enchantments#404]
What command/s am I supposed to use, that website does not help.

**Comment by badbones69** [comment]
If you want your players to be able to use the commands you need to give them permissions to those commands which the perms can be found here:
https://github.com/badbones69/Crazy-Enchantments/wiki/Commands-and-Permissions

**Comment by JoeTornadoz** [comment]
im still somewhat confused, do I need to type the perrmission thing somewhere? 

(sorry im new to server making and don't really know what im doing)

**Comment by badbones69** [comment]
Yes, you need to add the permissions to a permissions plugin. I suggest googling how to set up servers and learn how to use permission plugins. A lot of people like to use LuckPerms as their permission plugin. So I suggest looking up how to use it.
