### ISSUE TITLE
Some enchantments

### ISSUE THREAD

**Issue by samidont0817** [badbones69/Crazy-Enchantments#407]
I noticed that Ethereal, Vortex, and Soulbound were removed. If I were to add them from an older version would they be able to work? If not, is there any way I can re-add them to CrazyEnchantments? Thanks again for the help!

**Comment by badbones69** [comment]
All 3 of those enchantments never existed in this plugin. My guess is Ethereal and Vortex are renamed enchantments but I don't know what renamed enchantments those are.
Soulbound was never an enchantment in CE but was instead turned into an item called Protection Crystal by default but is still in CE.

**Comment by samidont0817** [comment]
So, Vortex is renamed. And I can't seem to find Ethereal. So I don't know where the other two came from. Thanks though. The only reason I asked is that on one of the older versions/other servers we have, they have these three enchantments that are in the enchantment.yml and all. That's all. Thanks~
