### ISSUE TITLE
Console Error [need help]

### ISSUE THREAD

**Issue by ReachBypass** [badbones69/Crazy-Enchantments#408]
Hey, I have the problem on my server that if I have so called ** permissions /ce I can use them without problems. But if a normal player without ** permissions comes up with an error when executing the command I have already completely reinstalled the plugin and it does not change anything and it still only works with ** permissions here the error: https://paste.kroseida.dev/piyubonofo.apache

**Comment by badbones69** [comment]
Strange, it seems to be coming from a plugin with this package `net.madgamble` but I can't tell if its an error on my end or that plugins end. I would show the developer of that plugin the error and see if he can't tell what's up because that code has no issue on all other servers.

**Comment by ReachBypass** [comment]
Hey, Core is our server cloud I'm currently doing my own game mode and need this plugin :/

**Comment by badbones69** [comment]
I figured it was a custom core for your server. I still think the issue is within that plugin. Have your developer look into that error on your plugin. Send him the error log.
