### ISSUE TITLE
console being spammed

### ISSUE THREAD

**Issue by Castiella** [badbones69/Crazy-Enchantments#411]
> >.... [10:15:01 ERROR]: Could not pass event PlayerInteractEvent to CrazyEnchantments v1.8-Dev-Build-v6.1
> java.lang.NullPointerException: null

here is the start up log:

[latest (2).log](https://github.com/badbones69/Crazy-Enchantments/files/3438054/latest.2.log)

**Comment by SoraShiunin** [comment]
Same issue https://pastebin.com/Zg90Rs8Y

**Comment by antoinech2** [comment]
Same for me
Paper Spigot 1.14.4 with Crazy-Enchantments 1.8-Dev-Build-v6.1

**Comment by badbones69** [comment]
Thanks for the reports guys.
Fixed and will be in the next release.
a646896022b1d43a01b146eac1c249e11c6f0271

**Comment by badbones69** [comment]
I just helped fix an issue that seems to be the same error as this issue #413. My guess is you guys broke the yaml format issue in the enchantments.yml. But I am unsure since I dont have ur files.

**Comment by Castiella** [comment]
I haven't edited my config since 1.13, but here is mine. 
[CrazyEnchantCOnfig.txt](https://github.com/badbones69/Crazy-Enchantments/files/3440618/CrazyEnchantCOnfig.txt)

**Comment by badbones69** [comment]
@Castiella I needed the enchantments.yml, not the config. Also, make sure to use https://pastebin.com next time instead of a file.

**Comment by Castiella** [comment]
https://pastebin.com/5EtY8RrS

my apologies

**Comment by Castiella** [comment]
@badbones69  was half asleep and didn't read your message properly

Here is the enchantments.yml https://pastebin.com/MC48c2aA

**Comment by badbones69** [comment]
@Castiella Seems ur file is fine so the next release should fix that error.

**Comment by antoinech2** [comment]
@badbones69 UP! The bug is still here and it's annoying ;(
