### ISSUE TITLE
Bad Config

### ISSUE THREAD

**Issue by Skullslice** [badbones69/Crazy-Enchantments#413]
hey Badbones69 i know i messed up somewhere in my enchantments config and I was wondering if you could have a look at it. One minute everything was working and I tried to separate some of the Enchants and the next minute my console was being spammed with "unable to pass any event" to CE I have tried to fix this on my own but all the yaml parsers say its valid so i'm at a loss.

Error:
https://pastebin.com/ir3s0Mqk
Enchants.yml:
https://pastebin.com/vHeqD9Bt

**Comment by badbones69** [comment]
You had a yaml format issue. I fixed them and now it should work fine.
https://pastebin.com/raw/nqJbiWiT

**Comment by Skullslice** [comment]
omg ty :D
