### ISSUE TITLE
overload and ninja hearts bug

### ISSUE THREAD

**Issue by mitchtheranga** [badbones69/Crazy-Enchantments#415]
if you have overload or ninja on a peice of armour and leave and reconnect to the server it will give you additional hearts and you will keep the amount you had before e.g. if you had 15 hearts before you relogged you would have 20 when you reconnected.

**Comment by badbones69** [comment]
This is due to another plugin not working with how potions affect a players max health. Ce does have an internal fix for this issue if you enable it in the config.yml.
https://github.com/badbones69/Crazy-Enchantments/blob/v1.8/plugin/src/main/resources/config1.13-Up.yml#L10
