### ISSUE TITLE
The category has no enchantments.

### ISSUE THREAD

**Issue by death2you-972** [badbones69/Crazy-Enchantments#417]
The category Common has no enchantments.
The category Rare has no enchantments.
The category Legendary has no enchantments.

also before you ask I do have them set up

any ideas?

https://pastebin.com/MAYVTGzs

**Comment by badbones69** [comment]
Pastebin ur enchantments.yml file for me.

**Comment by death2you-972** [comment]
Fixed it, by re-configuring everything, thank you for the awesome plugin dude
