### ISSUE TITLE
Ninja enchantment buggy

### ISSUE THREAD

**Issue by ghost** [badbones69/Crazy-Enchantments#419]
Hiya,

Cutting this right to the point: Ninja seems to be extremely buggy. I'm not sure if this is something that was raised before (a quick browse of the open issues leads me to believe that it _isn't_). That said, I'd like to report my issues.
- Equipping an item with Ninja causes it to potentially never apply the effects until a relog.
- When equipped, if the affects DO apply, they do NOT get removed. This persists THROUGH a relog, and requires milk to be drank or an /effect clear.

**Comment by badbones69** [comment]
What version of CE are you using?(Version numbers from /version crazyenchantments) 

Also what version of MC is your server?

**Comment by IxWolfie** [comment]
CE Version: 1.8-Dev-Build-v6.1
Server Version: 1.14.4 running build Paper#156 (latest).
