### ISSUE TITLE
MultiArrow Can Be Picked Up

### ISSUE THREAD

**Issue by Xuwznln** [badbones69/Crazy-Enchantments#422]
dev build 6.1
1.14.4 paper
the arrow shot by a bow with MultiArrow enchantment could be all picked up. Please fix that, thanks!

**Comment by HexedHero** [comment]
Confirmed, feel like it should just be removed due to the new vanilla enchant.

**Comment by Xuwznln** [comment]
No, the vanilla enchantment is MultiShot, not available for bows but crossbows. So this enchantment is still useful.

**Comment by Xuwznln** [comment]
tested, fixed in v7
