### ISSUE TITLE
Changing Level of Categories in Shop takes XP but does not give book

### ISSUE THREAD

**Issue by Unovic** [badbones69/Crazy-Enchantments#423]
Confirmed it by only changing the level. 
https://pastebin.com/862kGdwh

`[Server] INFO [Crazy Enchantments]>> The category Legendary has no enchantments. &7Please add enchantments to the category in the Enchantments.yml. If you do not wish to have the category feel free to delete it from the Config.yml`

Didn't change anything in the Enchantments.yml file.

On Paper 1.14.4
Using latest dev build
`[Server] INFO Plugins (22): ClearLag, CrazyAuctions, CrazyEnchantments, dynmap*, EpicRename, Essentials, EssentialsChat, EXPBank-6.0.0, FastAsyncWorldEdit, HolographicDisplays, IllegalStack, LuckPerms, mcMMO, OldCombatMechanics, PadLock, PlaceholderAPI*, SavageDeathChest, SilkSpawners, StackMob, Vault, WorldEdit, WorldGuard
`

**Comment by paz** [comment]
this is because of illegalstack

**Comment by badbones69** [comment]
I loaded your config onto my server will all default files except with your config. All three categories worked just fine grabbing from the /ce menu.

Do /version crazyenchantments and tell me the version number.
