### ISSUE TITLE
Hoe Enchants - BentoBox Support

### ISSUE THREAD

**Issue by LavRad** [badbones69/Crazy-Enchantments#426]
Hello,
Some of the new Hoe enchants seem to work on other people's islands (using BentoBox's BSkyBlock). The one I've seen working is GreenThumb.
Thanks!

**Comment by TwerkRekt** [comment]
it's only for 1.13 why do you need for this

**Comment by LavRad** [comment]
If “it’s only for 1.13” then why is the whole plugin being updated for 1.13-1.14 support? That’s the point in these Betas, and they’re betas for a reason - they may have issues that need to be fixed. This is an issue report.

**Comment by badbones69** [comment]
Ah, I see the issue. I forgot to add region checking. Ill make sure to fix this.
