### ISSUE TITLE
add support for 1.12.2 askyblock

### ISSUE THREAD

**Issue by TwerkRekt** [badbones69/Crazy-Enchantments#430]
hi
possibility to add support for askyblock? :c
the radiant enchantment is very cheat on the islands allows to kill the players
same for guards

plugin: https://www.spigotmc.org/resources/askyblock.1220/

**Comment by TwerkRekt** [comment]
and boom enchantments on bow allow to kill passive mob and players on island

**Comment by LavRad** [comment]
Since this is now a 1.13+ Supported plugin, why would ASkyBlock support be added when it isn’t intended for 1.13 use?

**Comment by TwerkRekt** [comment]
For the versions down of 1.13 logic no? wtf dude

**Comment by LavRad** [comment]
Alright. I didn’t notice that 1.8-1.12 was still supported, it looked like it wasn’t from the front page.
