### ISSUE TITLE
Wings enchantment __global__ region doesn't works.

### ISSUE THREAD

**Issue by clarkkentz** [badbones69/Crazy-Enchantments#431]
I can't get  __global__ to work with this enchantment

**Comment by MrApocalyptic** [comment]
If you want it to let them fly anywhere in a certain world theres an option to allow that http://prntscr.com/ozs427

**Comment by clarkkentz** [comment]
> If you want it to let them fly anywhere in a certain world theres an option to allow that http://prntscr.com/ozs427

Is that newest version or 1.7.9.4?
