### ISSUE TITLE
InventoryInteractEvent failing when previewing GKits.

### ISSUE THREAD

**Issue by justnohacks** [badbones69/Crazy-Enchantments#437]
When you right-click an item in the GKit GUI, you get the preview inventory. If the GKit name contains any colour (I have tested this), you can take items out of the inventory.

Spigot version: Spigot-1.13.2-0c02b0c-20190425-0538.jar (latest)
Plugin version: 1.8 Development 6.1 (also occurs in 6.2)

Error codes:
https://pastebin.com/wW38uMXE
https://pastebin.com/C68SH1xB

**Comment by badbones69** [comment]
Can u pastebin ur gkit file.

**Comment by justnohacks** [comment]
https://pastebin.com/5N5X9YpF

**Comment by badbones69** [comment]
Try the newest build from the Jenkins and see if that fixes it.
https://jenkins.badbones69.com

**Comment by justnohacks** [comment]
> Try the newest build from the Jenkins and see if that fixes it.
> https://jenkins.badbones69.com

Still doesn't work.
In addition, the prismarine crystal does not appear to have a name and a lore for navigating back to the menu.

**Comment by badbones69** [comment]
Alright, thanks I just found both issues and fixed them. It was to do with the back button I believe. Check the new build and let me know if that fixed ur issue.

**Comment by justnohacks** [comment]
Hi
I tested this on #37 and the issue still occurs. The back items are fixed now though.

**Comment by justnohacks** [comment]
I did some more testing and I concluded that items can only be taken out if the magic effect (&k) is present in the GKit and inventory name. It is fine with everything else.

**Comment by badbones69** [comment]
Can you pastebin the file that breaks.

**Comment by justnohacks** [comment]
https://pastebin.com/QHATiW62

**Comment by badbones69** [comment]
I have just tested with this file and it seems to have no issues. My best guess is another plugin might be causing an issue. You would need to have CE as the only plugin on ur server and then check if it still happens and if it does let me know and if it works instead then its one of those other plugins.

**Comment by justnohacks** [comment]
Alright, thanks for your help regardless.
I found that the following format codes caused the issue: &r, &m

P.S. - The lore on the fake items is not applying and displaying on items in the preview inventory.

**Comment by badbones69** [comment]
@justnohacks Thanks, fixed that lore issue. 

The issue with the color code is strange as for some reason it seems Minecraft does weird stuff with some of the color codes and am unsure why it does what it does with them and so it causes issues. I am looking into the issues with color code but am unsure whats going on.
