### ISSUE TITLE
books wont be given when buying

### ISSUE THREAD

**Issue by AnimatedJ** [badbones69/Crazy-Enchantments#438]
hi so the only thing i've changed in the config is the level price so its

common: 20
rare: 30
Legendary: 50

but when i reload the plugin and use /ce and i click on the rare or legendary the levels get taken and no book is given here is the paste bin

https://pastebin.com/pifLRqyR

i've also wanted to take out the fail chance out of it but i didnt find how

thanks for the help

**Comment by badbones69** [comment]
1. What version of CE are you using? Make sure to tell me the number from /version crazyenchantments and not the latest.

2. If you want to remove the destroy chance then just remove the placeholder from the book's lore.

**Comment by AnimatedJ** [comment]
1. im using 1.8-dev-build-v6.1

2.okay will do thanks

**Comment by badbones69** [comment]
Try and test to see if the v6.2 dev build on my Jenkins fixes the issue. I believe it does as its working fine on that version.
https://jenkins.badbones69.com/job/Crazy-Enchantments/

**Comment by AnimatedJ** [comment]
all fixed thanks
