### ISSUE TITLE
Enchantments bug and seed problems

### ISSUE THREAD

**Issue by vc606** [badbones69/Crazy-Enchantments#441]
1.While enchanting with Crazy-Enchantments,sometimes there will be an extra same effect.
ex:enchant stuff with Springs III and  AntiGravity III,it will become Springs III AntiGravity III and Spring I
and then Spring III will be covered by Spring I ,so the Spring effect is only I

2.When enchanted with Tiller or Planter and there is only 1 seed in inventory,the seed can be planted unlimited times

Version
Paper 1.14.4 #2​07
CrazyEnchantments[v1.8-Dev-Build-v6.2].jar #28

**Comment by vc606** [comment]
1.
I suspect  it is caused by that Antigravity and Springs in Enchantments.yml has the same translation.I will restart the server and try again later

**Comment by badbones69** [comment]
1. I put both on boots and they seem to be fine with no issue.

2. Make sure you're not in creative mode as creative mode is free all you can plant seeds.
