### ISSUE TITLE
Clicking on an item in GUI's picks them up instead (1.14.4)

### ISSUE THREAD

**Issue by ElGodyro** [badbones69/Crazy-Enchantments#443]
When i open any of the GUI's instead of showing information for the thing im clicking it picks the item up from the GUI [note : this happens both in op and default] !
I am using a couple of plugins which im not sure if i can mention if so please tell me .
Here is a Log error report https://paste.kroseida.dev/ozitusojeg.cs
And here is my config
https://paste.kroseida.dev/heyohosata.coffeescript

Its my first time working with plugins so i might not know much but i would appriciate any kind of help.

**Comment by badbones69** [comment]
The issue is your running CE v1.7.9.4 on a 1.14 server. v1.7.9.4 does **NOT** support 1.13+. You need to update to the dev builds to be able to use it on 1.13+.
