### ISSUE TITLE
Players get disabled enchantments

### ISSUE THREAD

**Issue by DarkObscurity** [badbones69/Crazy-Enchantments#444]
Hey! 

After the v7.1 we suddenly have the issues that people are getting CE books which are set to "False" in the enchantments config... If they receive a book that is set to false, they can't put it on their tool, so it's basically useless, but they do lose their XP... I have tried resetting all configs and stuff, but nothing seems to fix the issue.

**Comment by badbones69** [comment]
Thanks for the report, I just fixed the issue.
Commit: 53d80e5f9d15cc39f3f9a406551482bc19a62aa4
