### ISSUE TITLE
Resource/tps issue

### ISSUE THREAD

**Issue by DarkObscurity** [badbones69/Crazy-Enchantments#445]
Hello!

Recently we're experiencing some TPS loss issues on our server and I see CrazyEnchantments showing up in my timings reports. For example this event:

CrazyEnchantments::Event: m.b.c.e.Armor (PlayerMoveEvent)
count(62641)  total(22.82% 97.998s, 51.31% of tick)
avg(1.56ms per - 25.65ms/16.40 per tick)

Is there anything I can do to resolve these spikes or is this related to 1.14.4?

**Comment by badbones69** [comment]
What version of CE are you using?

**Comment by DarkObscurity** [comment]
This version:

https://jenkins.badbones69.com/job/Crazy-Enchantments/39/

**Comment by badbones69** [comment]
Try the newest build and let me know if that helps. I recoded the wings enchantment and so it should help with the issues a bit. If it continues try it with the wings particles turned off and it should help more.

**Comment by DarkObscurity** [comment]
I'll try that!

**Comment by DarkObscurity** [comment]
Well today we still see some spikes like these:

CrazyEnchantments::Event: m.b.c.e.Armor (PlayerMoveEvent)
count(2778)  total(21.13% 15.379s, 69.75% of tick)
avg(5.54ms per - 34.87ms/6.30 per tick)

It looks like they are happening around when a player joins and stuff gets applied or something?? We are running 1.14.4 which is terrible in general...

**Comment by gabenitez0** [comment]
El problema aún existe, alguna idea?
https://timings.aikar.co/?id=79b209e1e456498796e4abc4b58b9191
