### ISSUE TITLE
always success bug + enchantment does not give player head bug

### ISSUE THREAD

**Issue by minejango2** [badbones69/Crazy-Enchantments#450]
when I try add(not command) crazy enchantment at item, it always success.
and Decapitation or Headless doesn't give player head.
I try set 100% chance to enchantments, but it doesn't work
(1.13.2)

**Comment by badbones69** [comment]
CE version?

**Comment by minejango2** [comment]
Jenkins #47

**Comment by ScuroK** [comment]
is this bug still present?

**Comment by minejango2** [comment]
It fixed
