### ISSUE TITLE
when edit config file, enchant always success

### ISSUE THREAD

**Issue by minejango2** [badbones69/Crazy-Enchantments#454]
When I edit config.yml, the custom enchantments all successed.

**Comment by badbones69** [comment]
Pastebin the file you edited so I can see it.

**Comment by minejango2** [comment]
###################################
## Currency Types: https://github.com/badbones69/Crazy-Enchantments/wiki/Currency-Types
## Commands and Permissions: https://github.com/badbones69/Crazy-Enchantments/wiki/Commands-and-Permissions
## 1.9 and up players use these sounds: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
###################################################################
Settings:
  Prefix: '&8[&a대마법 부여&8]: ' #The prefix in the messages
  Update-Checker: true #Toggle on and off if you get an update message when you join if there is a new update.
  Player-Info-Backup-Message: true #Toggle this on and off if you wish to see when the player's data gets backed up.
  Reset-Players-Max-Health: true #This is for some servers that get a health duplication glitch from plugins like CombatTagPlus(v1.2.3 down)
  InvName: '&c&l대마법 부여대' #The name of the /CE inventory
  Enchantment-Book-Item: 'ENCHANTED_BOOK' #The item that the enchantment book is.
  Enchantment-Book-Glowing: true #Toggle on or off if the book will have an enchanted look.
  GUISize: 54 #The size of the GUI, must be a factor of 9
  EnchantmentBookLore: #The lore on the enchantments books.
    - '&7아이템에 대마법 부여책을 두세요'
    - '&7마우스 우클릭으로 정보를 볼 수 있습니다'
    - ''
    - '%description%'
    - ''
    - '&a%success_rate%%&f/&4%destroy_rate%%'
  LostBook: #Lost book options.
    Item: 'BOOK' #The item the lost books are.
    Name: '%category%&b&l 대마법 부여책' #The name of the lost books.
    Lore: #The lore of the lost books.
      - '%category%&7 대마법 부여책이다'
      - '&7마우스 우클릭으로 뽑을 수 있다.'
  Scrambler:
    Item: 'PAPER' #The item it will be.
    Glowing: true #If it has a glowing effect.
    Name: '&e&l확률 재조정 주문서' #The name of the item.
    Lore: #The lore of the item.
      - '&7대마법 부여책의 확률을'
      - '&7재조정하는 주문서이다.' 
    GUI: #Options for the GUI.
      Name: '&8확률 재조정 &e주문서' #Name of the GUI.
      Toggle: false #If the GUI will show. Warning>> This may cause lag if a lot of players are using it all the time.
      Pointer: #The pointer in the middle of the GUI.
        Item: 'REDSTONE_TORCH' #The item the pointer is.
        Name: '&c&l포인터' #The name of the pointer.
        Lore: #The lore on the pointer.
          - '&7Whatever percents the item lands on'
          - '&7will be the new percents on your book.'
    InGUI: true #If you can buy it in the GUI.
    Slot: 23 #The slot the item will be in.
    GUIName: '&e&l확률 재조정 주문서' #Name of the item in the GUI.
    GUILore: #The lore of the item in the GUI.
      - '&7대마법 부여책의 확률을'
      - '&7재조정하는 주문서이다.' 
      - ''
      - '&e가격: &e&l5000원'
  GKitz: #GKitz GUI option.
    InGUI: false #If you can open the GKitz GUI from the main /ce gui.
    Enabled: false #If the GKitz option is enabled on the server.
    Slot: 1 #The slot it will be in.
    Item: 'DIAMOND_CHESTPLATE' #The item it is.
    Glowing: true #If it has a glowing effect.
    Name: '&c&l' #The name of the item.
    Lore: #The lore of the item.
      - '&b>>&7&n클릭하여 여세요&b<<'
  ProtectionCrystal:
    InGUI: true #If it's in the GUI.
    Slot: 39 #Slot it is in
    Item: 'DIAMOND' #Item it is
    Glowing: true #If it has a glowing effect.
    Protected: '&6보호됨 [보석]' #The lore that goes on the item that is protected.
    Lose-Protection-On-Death: false #If true then when the player dies they get the item but it loses its protection.
    Chance: #The option to allow protection to fail.
      Toggle: false #Toggle if the protection has a chance of failing.
      Success-Chance: 75 #The chance that the protection will work.
    Name: '&6&l보호의 &b&l보석' #Name of the item
    Lore: #Lore of the item
      - '&7대마법의 부작용으로부터'
      - '&7아이템을 보호해주는 보석이다.'
      - ''
      - '아이템 위에 놓으세요.'
    GUIName: '&6&l보호의 &b&l보석'
    GUILore:
      - '&7대마법의 부작용으로부터'
      - '&7아이템을 보호해주는 보석이다.'
      - ''
      - '&e가격: &e&l5000원'
  BlackSmith: #Options for the Black Smith
    InGUI: true #In the GUI.
    Slot: 16 #Slot it is in.
    Item: 'ANVIL' #Item that shows in the GUI
    Glowing: true #If it has a glowing effect.
    Name: '&b&l대마법 &7&l모루' #Name of the Item in the GUI
    Lore: #Lore on the item.
      - '&b>>&7&n대마법 합치기&b<<'
    GUIName: '&8&l대마법 모루' #Name of the Black Smith's GUI
    Results:
      None: '&c&l합치기 불가' #Name of the item when there are no results in the Black Smith
      Not-Found-Lore:
        - '&7합칠 수 없음.'
        - '&7레벨과 종류가 똑같은'
        - '&7대마법이나 대마법이 부여된'
        - '&7아이템을 두어야 합니다'
      Found: '&c&l가격: &6&l%cost%XP' #The lore at the bottom of the item
    Transaction: #Options for the pricing
      Currency: XP_Level
      Costs: #Cost options
        Power-Up: 5 #When an enchantment levels up 1 on an item
        Add-Enchantment: 3 #When it adds an enchantment to the item from another item
        Book-Upgrade: 5 #Leveling up the power of a book
  Tinker: #Settings for Info item in the GUI
    InGUI: true #Toggle whether it is in the /CE GUI or not
    Slot: 12 #Slot it is in
    Item: 'GUNPOWDER' #Item it is
    Glowing: false #If it has a glowing effect.
    Name: '&7&l가루 연금술' #Name of the Item
    Lore: #Lore of the item
      - '&b>>&7&n펼쳐보기&b<<'
  Info: #Settings for Info item in the GUI
    InGUI: true #Toggle whether it is in the /CE GUI or not
    Slot: 14 #Slot it is in
    Item: 'COMPASS' #Item it is
    Glowing: true #If it has a glowing effect.
    Name: '&e대마법 사전' #Name of the Item
    Lore: #Lore of the item
      - '&b>>&7&n펼쳐보기&b<<'
  Dust: #Settings for the Magical Dust
    MysteryDust:
      Item: 'GUNPOWDER' #Item mystery dust is
      Name: '&7의문의 대마법 가루' #Name of the dust
      Lore: #Use %percent% to set the percent
        - '&a1-%percent%%의'
        - '&a성공의 대마법 가루&7나 &e보호의 대마법 가루&7를'
        - '&7마우스 우클릭하여 얻을 수 있다'
      Firework:
        Toggle: true #Toggle if the firework happens on open.
        Colors: 'Black, White, Red' #The colors the firework will be.
      Dust-Toggle:
        Success: true #Toggle whether you can get success dust from Mystery Dust.
        Destroy: true #Toggle whether you can get destroy dust from Mystery Dust.
        Failed: true #Toggle whether you can get failed dust from Mystery Dust.
      PercentRange: #Range the mystery rate will be.
        Max: 30 #Max percent
        #Min will always be 1.
    SuccessDust:
      InGUI: false #If you can buy it in the /CE GUI
      GUIName: '&a성공의 대마법 가루' #Name of the item in the GUI
      GUILore: #Lore in the GUI.
        - '&e가격: &a&l$500'
        - '&7대마법 부여책의 마법 부여 성공 확률을'
        - '&7&e%percent%% &7늘린다'
      Slot: 25 #Slot number it is on
      Item: 'SUGAR' #Item the dust is
      Name: '&a성공의 대마법 가루' #Name of the dust
      Lore: #Lore for the dust
        - '&a성공할 확률 +%percent%%'
        - '&7대마법 부여책의 마법 부여 성공 확률을'
        - '&7&e%percent%% &7늘린다'
      PercentRange: #Range the success rate will be.
        Max: 30 #Max percent
        Min: 2 #Minimum percent
    DestroyDust:
      InGUI: false #If you can buy it in the /CE GUI
      GUIName: '&e보호의 대마법 가루' #Name of the item in the GUI
      GUILore: #Lore in the GUI.
        - '&e가격: &a&l$500'
        - '&7대마법 부여책의 마법 부여 실패 확률을'
        - '&e%percent%% &7줄인다'
      Slot: 40 #Slot number it is on
      Item: 'REDSTONE' #Item the dust is
      Name: '&e보호의 대마법 가루' #Name of the dust
      Lore: #Lore for the dust
        - '&c부서질 확률 -%percent%%'
        - '&7대마법 부여책의 마법 부여 실패 확률을'
        - '&7&e%percent%% &7줄인다'
      PercentRange: #Range the destroy rate will be.
        Max: 10 #Max percent
        Min: 2 #Minimum percent
    FailedDust:
      Item: 'GUNPOWDER' #Item the dust is
      Name: '&7불량 대마법 가루' #Name of the dust
      Lore: #Lore for the dust
        - '&7대마법 가루 실패작이다'
        - '&7...누군가 이걸 모으고 있다.'
  BlackScroll: #Settings for the black scrolls
    Item: 'INK_SAC' #The item the black scroll can be
    Name: '&8&l&nBlack Scroll' #The name of the black scroll
    Item-Lore: #The lore that will be on the black scroll.
      - '&7Have a custom enchantment you don''t want?'
      - '&7Drag and drop this on an item with a custom enchantment'
      - '&7and it will remove a random enchantment for you.'
      - '&7&l(&6&l!&7&l) &7Only works on Custom Enchantments.'
    Chance-Toggle: false #Toggle on and off if the black scrolls have a chance of failing.
    Chance: 75 #The chance that the black scroll will work.
    InGUI: false #Toggle being able to buy in the /CE GUI. Cost is controlled in the SignOptions section
    GUIName: '&7Black Scroll'
    Glowing: false #If it has a glowing effect.
    Slot: 21 #Slot you can buy the scroll at
    Lore: #Lore of the item in the GUI
      - '&e가격: &a&l1000원'
      - '&7Black Scrolls allow you to'
      - '&7take off random enchantments.'
    SuccessChance: #Controls what the success chance will be when they get the book from the Black Scroll
      Max: 75 #The Max percent
      Min: 35 #The Minimum percent
    DestroyChance: #Controls what the destroy chance will be when they get the book from the Black Scroll
      Max: 25 #The Max percent
      Min: 5 #The Minimum percent
  WhiteScroll:
    Item: 'ENCHANTED_BOOK' #The item the white scroll is.
    Name: '&a&l보호의 책' #The name of the white scrolls.
    Item-Lore: #The lore that will be on the white scroll.
      - '&7대마법의 부작용으로부터'
      - '&7아이템을 보호해주는 책이다.'
    InGUI: false #Toggle being able to buy in the /CE GUI. Cost is controlled in the SignOptions section
    GUIName: '&a&l보호의 책'
    Glowing: false #If it has a glowing effect.
    Slot: 43 #Slot you can buy the scroll at
    Lore: #Lore of the scroll in the GUI
      - '&e가격: &a&l2000원'
      - '&7대마법의 부작용으로부터'
      - '&7아이템을 보호해주는 책이다.'
    ProtectedName: '&a보호됨 [주문]' #The lore that is added to protect an item.
  TransmogScroll:
    Item: 'QUARTZ' #The item the scroll is.
    Name: '&d&lTransmog Scroll' #The name of the scroll.
    Item-Lore: #The lore that will be on the scroll.
      - '&7This scroll allows you to organize'
      - '&7your enchantments and tell you how many'
      - '&7enchantments you currently have on the item.'
    InGUI: false #Toggle being able to buy in the /CE GUI. Cost is controlled in the SignOptions section
    GUIName: '&dTransmog Scroll'
    Glowing: false #If it has a glowing effect.
    Slot: 30 #Slot you can buy the scroll at
    Lore: #Lore of the scroll in the GUI
      - '&e가격: &a&l$200'
      - '&7This scroll allows you to organize'
      - '&7your enchantments and tell you how many'
      - '&7enchantments you currently have on the item.'
    Amount-of-Enchantments: ' &7[&6&n%amount%&7]' #The suffix that will be added at the end of the item's name.
    Amount-Toggle: true #If the amount is added to the suffix of the item's name.
    Count-Vanilla-Enchantments: true #If it counts the vanilla enchantments in the amount.
  EnchantmentOptions: #Options for enchanted books.
    MaxAmountOfEnchantmentsToggle: true #Turn on and off the Max amount of enchantments. Use crazyenchantments.limit.# permission to set the limit.
    IncludeVanillaEnchantments: false #Count Vanilla enchantments also.
    Enchant-Stacked-Items: false #Turn on if you wish for enchantment books to enchant stacked items.
    MaxRageLevel: 4 #The max amount of rage that scan stack when fighting.
    Break-Rage-On-Damage: true #If the player is damaged while building rage, it will be broken if this is enabled.
    Right-Click-Book-Description: true #Toggles whether when you right-click the enchantment book if it messages the player the description or not.
    UnSafe-Enchantments: true #Having this set to true will allow players to use enchantments levels above the max level.
    Blast-Full-Durability: true #Toggle if the item takes damage for every block it breaks or just one. True to take full damage or false to take only 1 damage.
    Right-Click-Enchantment-Table: false #When set to true if a player right-clicks an enchantment table it will open the /ce GUI.
    EXP-Bug: false #Only needs to be true if the player's XP sometimes glitches to 1Bill after buying an item with all their XP.
    Lightning-Sound-Range: 160 #Range in blocks where the lightning sound should become inaudible.
    Armor-Upgrade: #Having this enabled will allow players to try and add a higher level of an enchantment onto an item with a lower level of the enchantment.
      Toggle: true #Toggle on or off the ability to upgrade the enchantments.
      Enchantment-Break: false #If the book's destroy rate happens the item doesn't break but instead the current lower version of the enchantment is destroyed. If false then the item will be destroyed instead.
    Wings: #Options for the Wings Enchantment.
      Clouds: false #Toggle if the wings enchantment shows particles under the player's feet. Warning this option has been known to cause lag so toggle it off if you get lag.
      Enemy-Toggle: false #This toggles on and off the wings enchantment when an enemy is close to the player.
      Distance: 25 #How far away the enemy has to be to toggle off the enchantment.
      Members-Can-Fly: true #Toggle if a player is a member of a world guard region if they can fly.
      Owners-Can-Fly: true #Toggle if a player is an owner of a world guard region if they can fly.
      Regions: #All world guard regions the Wings enchantment can work in.
        - 'world'
        - 'world_nether'
        - 'world_the_end'
      Worlds: #The option to disable/enable wings in worlds.
        Limitless-Flight-Worlds: #Worlds that players are allowed to fly for a limitless amount of time. This bypasses enemy checks as well.
          - 'Hub_Example'
        Whitelisted: #If the player has wings enchantment in these worlds they will be able to fly anywhere regardless of regions/enemies.
          - 'world'
          - 'world_nether'
          - 'world_the_end'
        Blacklisted: #Wings will not work at all in these worlds regardless of regions.
          - 'SkyBlock_Example'
  Costs: #This is where you set the cost of stuff in the shop GUI.
    Scrambler: #The item that is being bought.
      Cost: 5000 #How much the item will cost.
      Currency: Vault #The currency that will be taken when bought.
    ProtectionCrystal:
      Cost: 5000
      Currency: Vault
    TransmogScroll:
      Cost: 200
      Currency: Vault
    BlackScroll:
      Cost: 1000
      Currency: Vault
    WhiteScroll:
      Cost: 5000
      Currency: Vault
    SuccessDust:
      Cost: 500
      Currency: Vault
    DestroyDust:
      Cost: 500
      Currency: Vault
  SignOptions: #Options for the Signs.
    CategoryShopStyle: #What the sign will look like. The price will be determined by the category you pick
      Line1: '&b&l대마법 부여' #Line 1 of the sign
      Line2: '&b&l상점:' #Line 2 of the sign
      Line3: '&l%category%' #Line 3 of the sign
      Line4: '&c&l가격: &6&l%cost%XP' #Line 4 of the sign
      Buy-Message: '&7You have just bought an enchantment book, and it is %bookname%&7 from the %category%&7 tier.'
    ProtectionCrystalStyle:
      Line1: '&b&lCrazy Enchant'
      Line2: '&b&lShop:'
      Line3: '&5&lProtection &b&lCrystal'
      Line4: '&c&l가격: &a&l$500'
      Buy-Message: '&7You have just bought a &5&lProtection &b&lCrystal.' #Message when buying an item.
    ScramblerStyle:
      Line1: '&b&lCrazy Enchant'
      Line2: '&b&lShop:'
      Line3: '&e&lScrambler'
      Line4: '&c&l가격: &a&l$800'
      Buy-Message: '&7You have just bought a &e&lThe Grand Scrambler&7.' #Message when buying an item.
    SuccessDustStyle:
      Line1: '&b&lCrazy Enchant'
      Line2: '&b&lShop:'
      Line3: '&e&lMagical Angel Dust'
      Line4: '&c&l가격: &a&l$500'
      Buy-Message: '&7You have just bought a &aMagical Angel Dust&7.'
    DestroyDustStyle:
      Line1: '&b&lCrazy Enchant'
      Line2: '&b&lShop:'
      Line3: '&e&lMagical Fixing Dust'
      Line4: '&c&l가격: &a&l$500'
      Buy-Message: '&7You have just bought a &eMagical Fixing Dust&7.'
    BlackScrollStyle:
      Line1: '&b&lCrazy Enchant'
      Line2: '&b&lShop:'
      Line3: '&4&lBlack &8&lScrolls'
      Line4: '&c&l가격: &a&l$1000'
      Buy-Message: '&7You have just bought a &8&l&nBlack Scroll&7.'
    WhiteScrollStyle:
      Line1: '&b&lCrazy Enchant'
      Line2: '&b&lShop:'
      Line3: '&f&lWhite &b&lScrolls'
      Line4: '&c&l가격: &a&l$2000'
      Buy-Message: '&7You have just bought a &e&lWhite Scroll&7.'
    TransmogScrollStyle:
      Line1: '&b&lCrazy Enchant'
      Line2: '&b&lShop:'
      Line3: '&d&lTransmog &b&lScrolls'
      Line4: '&c&l가격: &a&l$200'
      Buy-Message: '&7You have just bought a &d&lTransmog Scroll&7.'
  #####################
  # Slot:<Slot> - The slot the item will go in.
  # Item:<Item Name> - The item that it will be. You can use meta data for the items. List of names: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
  # Name:<Name> - The name that will go on the item.
  # Lore:<Line1>,<Line2>,<Line3>,<Line4> - The lore can use multiple lines by adding a , in-between letters. Example: "Lore:&7I am line1,&aI am line 2,&eI am line3"
  #Placeholders can be used in the name and lore and they must be lowercase.
  #Placeholders: %vault% %xp_level% %xp_total%
  #####################
  GUICustomization: #This allows you to customize unclickable items into your GUI.
    - 'Slot:1, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:2, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:3, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:4, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:5, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:6, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:7, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:8, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:9, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:10, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:18, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:19, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:27, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:28, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:36, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:37, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:45, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:46, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:47, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:48, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:49, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:50, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:51, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:52, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:53, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:54, Item:BLACK_STAINED_GLASS_PANE, Name: '
Categories: #You can make as many different categories as you want
  Common: #Name of the category
    Name: '&a&l&n하급' #Name in the GUI
    Slot: 29 #The Slot number the item will be in
    InGUI: false #Toggle if it's in the GUI or not.
    Lore: #The lore of the Item
      - '&e가격: &6경험치 &6&l60'
    Item: 'LIME_STAINED_GLASS_PANE' #The id for the item
    Glowing: true #If it has a glowing effect.
    Cost: 20 #How much each book will cost to buy.
    Currency: XP_Level #The currency you wish to use.
    Rarity: 1 #This allows the enchantments to be ordered with the Transmog Scrolls. The higher the number the rarer it is. Try and have each category have different rarities.
    LostBook: #Controls the Lost Book shop for this tier
      InGUI: true #If it shows in the /CE Gui
      Slot: 29 #Slot it will be in
      Item: 'LIME_STAINED_GLASS_PANE' #The item that is shown in the GUI
      Glowing: true #Is it enchanted
      Name: '&a&l&n하급' #Name of the item
      Lore: #Lore on the item
        - '&e가격: &6경험치 &6&l400'
        - '&7랜덤 &a&l&n하급&7 책 부여.'
      Cost: 400
      Currency: XP_total
      FireworkToggle: true #Toggle on and off if when opening a lost book a firework effect happens
      FireworkColors: 'White, Lime' #The colors of the firework
      Sound-Toggle: false
      Sound: 'BLOCK_ANVIL_PLACE'
    EnchOptions: #Enchantment Options
      SuccessPercent: #The range for the success rate that the enchantment will have
        Max: 100 #The max success rate
        Min: 10 #The min success rate
      DestroyPercent: #The range for the destroy rate that the enchantment will have
        Max: 30 #The max destroy rate
        Min: 0 #The min destroy rate
      MaxLvlToggle: true #Turn on and off Max Level cap
      LvlRange: #The range of levels that can be found in the Category.
        Max: 10
        Min: 1
  Rare:
    Name: '&9&l&n중급'
    Slot: 30
    InGUI: false
    Lore:
      - '&e가격: &6경험치 &6&l60'
    Item: 'BLUE_STAINED_GLASS_PANE'
    Glowing: true
    Cost: 40
    Currency: XP_Level
    Rarity: 2
    LostBook:
      InGUI: true
      Slot: 30
      Item: 'BLUE_STAINED_GLASS_PANE'
      Glowing: true
      Name: '&9&l&n중급'
      Lore:
        - '&e가격: &6경험치 &6&l2000'
        - '&7랜덤 &9&l&n중급&7 책 부여.'
      Cost: 2000
      Currency: XP_total
      FireworkToggle: true
      FireworkColors: 'White, Blue'
      Sound-Toggle: false
      Sound: 'BLOCK_ANVIL_PLACE'
    EnchOptions:
      SuccessPercent:
        Max: 100
        Min: 10
      DestroyPercent:
        Max: 30
        Min: 0
      MaxLvlToggle: true
      LvlRange:
        Max: 10
        Min: 1
  Epic:
    Name: '&4&l&n상급'
    Slot: 31
    InGUI: false
    Lore:
      - '&e가격: &6경험치 &6&l'
    Item: 'RED_STAINED_GLASS_PANE'
    Glowing: true
    Cost: 60
    Currency: XP_total
    Rarity: 3
    LostBook:
      InGUI: true
      Slot: 31
      Item: 'RED_STAINED_GLASS_PANE'
      Glowing: true
      Name: '&4&l&n상급'
      Lore:
        - '&e가격: &6경험치 &6&l5000'
        - '&7랜덤 &4&l&n상급&7 책 부여.'
      Cost: 5000
      Currency: XP_total
      FireworkToggle: true
      FireworkColors: 'White, Red'
      Sound-Toggle: false
      Sound: 'BLOCK_ANVIL_PLACE'
    EnchOptions:
      SuccessPercent:
        Max: 100
        Min: 10
      DestroyPercent:
        Max: 30
        Min: 5
      MaxLvlToggle: true
      LvlRange:
        Max: 10
        Min: 1
  Random:
    Name: '&e&l&n랜덤'
    Slot: 32
    InGUI: false
    Lore:
      - '&e가격: &6XP Levels &6&l60'
    Item: 'YELLOW_STAINED_GLASS_PANE'
    Glowing: false
    Cost: 60
    Currency: XP_total
    Rarity: 4
    LostBook:
      InGUI: true
      Slot: 32
      Item: 'YELLOW_STAINED_GLASS_PANE'
      Glowing: true
      Name: '&e&l&n랜덤'
      Lore:
        - '&e가격: &6경험치 &6&l3000'
        - '&7모든 등급(전설 제외)의 책이 나온다.'
      Cost: 3000
      Currency: XP_total
      FireworkToggle: true
      FireworkColors: 'White, Yellow'
      Sound-Toggle: false
      Sound: 'BLOCK_ANVIL_PLACE'
    EnchOptions:
      SuccessPercent:
        Max: 100
        Min: 10
      DestroyPercent:
        Max: 30
        Min: 5
      MaxLvlToggle: true
      LvlRange:
        Max: 10
        Min: 1
  Legendary:
    Name: '&6&l&n전설'
    Slot: 34
    InGUI: false
    Lore:
      - '&e가격: &6XP Levels &6&l60'
    Item: 'ORANGE_STAINED_GLASS_PANE'
    Glowing: false
    Cost: 60
    Currency: XP_total
    Rarity: 5
    LostBook:
      InGUI: true
      Slot: 34
      Item: 'ORANGE_STAINED_GLASS_PANE'
      Glowing: true
      Name: '&6&l&n전설'
      Lore:
        - '&e가격: &6경험치 &6&l15000'
        - '&7랜덤 &6&l&n전설&7 책 부여.'
      Cost: 15000
      Currency: XP_total
      FireworkToggle: true
      FireworkColors: 'White, Orange'
      Sound-Toggle: false
      Sound: 'BLOCK_ANVIL_PLACE'
    EnchOptions:
      SuccessPercent:
        Max: 100
        Min: 10
      DestroyPercent:
        Max: 30
        Min: 5
      MaxLvlToggle: true
      LvlRange:
        Max: 10
        Min: 1
  Trash:
    Name: '&8&l&n폐기'
    Slot: 35
    InGUI: false
    Lore:
      - '&e가격: &6XP Levels &6&l60'
    Item: 'YELLOW_STAINED_GLASS_PANE'
    Glowing: false
    Cost: 60
    Currency: XP_total
    Rarity: 6
    LostBook:
      InGUI: true
      Slot: 35
      Item: 'GRAY_STAINED_GLASS_PANE'
      Glowing: true
      Name: '&8&l&n폐기'
      Lore:
        - '&e가격: &6경험치 &6&l99999999'
        - '&7사기이거나 일반 마법과 겹쳐'
        - '&7금지된 책이다. 뽑지 않는걸 추천한다.'
      Cost: 99999999
      Currency: XP_total
      FireworkToggle: true
      FireworkColors: 'White, Gray'
      Sound-Toggle: false
      Sound: 'BLOCK_ANVIL_PLACE'
    EnchOptions:
      SuccessPercent:
        Max: 100
        Min: 10
      DestroyPercent:
        Max: 30
        Min: 5
      MaxLvlToggle: true
      LvlRange:
        Max: 10
        Min: 1


(Encoding to ANSL)

**Comment by minejango2** [comment]
+20191221 when I change the 'EnchantmentBookLore' in config, enchant always success.

**Comment by badbones69** [comment]
The issue is you have to have the Success and Destroy placeholders on 2 different lines.
Example:
```yaml
  EnchantmentBookLore: #The lore on the enchantments books.
    - '&7æ∆¿Ã≈€ø° ¥Î∏∂π˝ ∫Œø©√•¿ª µŒººø‰'
    - '&7∏∂øÏΩ∫ øÏ≈¨∏Ø¿∏∑Œ ¡§∫∏∏¶ ∫º ºˆ ¿÷Ω¿¥œ¥Ÿ'
    - ''
    - '%description%'
    - ''
    - '&a%success_rate%%'
    - '&4%destroy_rate%%'
```

Also next time pastebin your files instead of sending a zip.
