### ISSUE TITLE
Blast enchantment don't give ores

### ISSUE THREAD

**Issue by Corenb** [badbones69/Crazy-Enchantments#457]
Hello,

I've tried the latest build and blast enchantment work again but don't give any ore block with AutoSmelt and Furnace enchantments.
I'm using spigot/paper 1.15

**Comment by badbones69** [comment]
Try the newest CE dev build as while testing this those enchantments are working just fine.

https://jenkins.badbones69.com/

**Comment by Xuwznln** [comment]
Latest release version on github and paper 1.15.1.
When having Blast and AutoSmelt at the same time, ores just disappear but give some experience.

**Comment by badbones69** [comment]
Fixed: f769ef321c7cec8b3987fecffc1995f524acd013
