### ISSUE TITLE
ProjectileHitEvent Console Error Spam

### ISSUE THREAD

**Issue by luiswenner** [badbones69/Crazy-Enchantments#459]
I am repeatedly experiencing this error on my console without stopping. I do not know what it is, I have already corrected but the error persists
https://pastebin.com/Wmi9zJRf

**Comment by badbones69** [comment]
Can you pastebin your log file.

**Comment by luiswenner** [comment]
https://pastebin.com/yV8JgP1q

**Comment by luiswenner** [comment]
Any solution ?

**Comment by badbones69** [comment]
This should be fixed but if not let me know.

**Comment by luiswenner** [comment]
> This should be fixed but if not let me know.

OK, thanks for your attention.  and yes I will be aware
