### ISSUE TITLE
How can I see advanced information of enchantments?

### ISSUE THREAD

**Issue by therichyxd** [badbones69/Crazy-Enchantments#460]
Hi, I would like to know how to get more information about each of the enchantments, such as I read on the web that the fortify enchantment is 1/13 likely to work while the voodoo enchantment is 1/7 likely. I've been searching the page and I haven't found anything. Where can I access this information?

**Comment by badbones69** [comment]
It depends on the version of CE your using. The newer 1.8 builds allow editing of the chances if they use the chance. The chance system is out of 100%.

Example:
https://github.com/badbones69/Crazy-Enchantments/blob/v1.8/plugin/src/main/resources/Enchantments.yml#L84-L86
