### ISSUE TITLE
Remove enchantment level description (?)

### ISSUE THREAD

**Issue by Anastyment** [badbones69/Crazy-Enchantments#467]
Hi! as the tittle says... Its possibel to remove the enchantment level description? (I, II, III, IV, V...)
Like this... ^^

• From:
![1](https://user-images.githubusercontent.com/60352248/74610746-c1076e80-50d4-11ea-89ed-45bda4045cec.png)

• To:
![2](https://user-images.githubusercontent.com/60352248/74610766-f0b67680-50d4-11ea-915f-0fac3c6b3b70.png)

Just for make something like this. (Example :S)
![3](https://user-images.githubusercontent.com/60352248/74610936-70911080-50d6-11ea-8e35-4a83d45cd3a4.png)

Greetings!

**Comment by badbones69** [comment]
There is no option to make the level disappear as it is needed to know what level the enchantment is.
