### ISSUE TITLE
Crazy Enchantment HellForged didn't work

### ISSUE THREAD

**Issue by minejango2** [badbones69/Crazy-Enchantments#471]
I walk and walk... but still durability doesn't filled.

**Comment by badbones69** [comment]
CE version and MC version.

**Comment by minejango2** [comment]
CrazyEnchantments v1.8-Dev-Build-v8.1-Build#82, 1.15.2

**Comment by badbones69** [comment]
Alright, I'll take a look into this when I have a bit of time.

**Comment by badbones69** [comment]
Fixed: 9119c6c789daa1a44630c507ffe7c4f004770f25
