### ISSUE TITLE
Maven error

### ISSUE THREAD

**Issue by mrkino99** [badbones69/Crazy-Enchantments#476]
When do mvn clean install with the source code of this plugin, it says me that PreciusStones arent find
What should i do?

**Comment by mrkino99** [comment]
ok, i found its repository. now, why massivecraft is needed? i cant find it the repository for this plugin lol

**Comment by badbones69** [comment]
Answered via discord.

![](https://user-images.githubusercontent.com/5057118/75131856-bd5e8380-56a2-11ea-95af-2e95d4d03e95.jpg)
