### ISSUE TITLE
Armor Crazy Enchantment add to Player Head

### ISSUE THREAD

**Issue by minejango2** [badbones69/Crazy-Enchantments#477]
Armor enchantment to Skull

**Comment by badbones69** [comment]
If you wish to add heads and other items to helmets then just add the item name here:
https://github.com/badbones69/Crazy-Enchantments/blob/v1.8/plugin/src/main/resources/Enchantment-Types1.13-Up.yml#L15

**Comment by minejango2** [comment]
I can put enchants there, but it doesnt work.

**Comment by badbones69** [comment]
Pastebin your Enchantment types file then.

**Comment by minejango2** [comment]
Info-GUI-Settings:
  Inventory:
    Name: '&c&l대마법 정보'
    Size: 27
  Back-Item:
    Right:
      Item: 'NETHER_STAR'
      Name: '&7&l<<&b&l이전'
      Lore: []
    Left:
      Item: 'NETHER_STAR'
      Name: '&b&l이전&7&l>>'
      Lore: []
Types:
  Helmet:
    Display-Item:
      Item: 'DIAMOND_HELMET'
      Slot: 1
      Name: '&e&l투구 대마법'
      Lore:
        - '&7대마법 부여가 가능한 장비'
        - '&a- 가죽 모자'
        - '&a- 사슬 투구'
        - '&a- 황금 투구'
        - '&a- 철 투구'
        - '&a- 다이아몬드 투구'
        - '&a- 거북 등딱지'
    Enchantable-Items:
      - 'LEATHER_HELMET'
      - 'CHAINMAIL_HELMET'
      - 'GOLDEN_HELMET'
      - 'IRON_HELMET'
      - 'DIAMOND_HELMET'
      - 'TURTLE_HELMET'
      - 'PLAYER_HEAD'
  Boots:
    Display-Item:
      Item: 'DIAMOND_BOOTS'
      Slot: 2
      Name: '&e&l부츠 대마법'
      Lore:
        - '&7대마법 부여가 가능한 장비'
        - '&a- 가죽 부츠'
        - '&a- 사슬 부츠'
        - '&a- 황금 부츠'
        - '&a- 철 부츠'
        - '&a- 다이아몬드 부츠'
    Enchantable-Items:
      - 'LEATHER_BOOTS'
      - 'CHAINMAIL_BOOTS'
      - 'GOLDEN_BOOTS'
      - 'IRON_BOOTS'
      - 'DIAMOND_BOOTS'
  Armor:
    Display-Item:
      Item: 'DIAMOND_CHESTPLATE'
      Slot: 3
      Name: '&e&l갑옷 대마법'
      Lore:
        - '&7대마법 부여가 가능한 장비'
        - '&a- 가죽 갑옷'
        - '&a- 사슬 갑옷'
        - '&a- 황금 갑옷'
        - '&a- 철 갑옷'
        - '&a- 다이아몬드 갑옷'
    Enchantable-Items:
      - 'LEATHER_HELMET'
      - 'CHAINMAIL_HELMET'
      - 'GOLDEN_HELMET'
      - 'IRON_HELMET'
      - 'DIAMOND_HELMET'
      - 'LEATHER_CHESTPLATE'
      - 'CHAINMAIL_CHESTPLATE'
      - 'GOLDEN_CHESTPLATE'
      - 'IRON_CHESTPLATE'
      - 'DIAMOND_CHESTPLATE'
      - 'LEATHER_LEGGINGS'
      - 'CHAINMAIL_LEGGINGS'
      - 'GOLDEN_LEGGINGS'
      - 'IRON_LEGGINGS'
      - 'DIAMOND_LEGGINGS'
      - 'LEATHER_BOOTS'
      - 'CHAINMAIL_BOOTS'
      - 'GOLDEN_BOOTS'
      - 'IRON_BOOTS'
      - 'DIAMOND_BOOTS'
  Bow:
    Display-Item:
      Item: 'BOW'
      Slot: 4
      Name: '&e&l활 대마법'
      Lore:
        - '&7대마법 부여가 가능한 장비'
        - '&a- 활'
    Enchantable-Items:
      - 'BOW'
  Sword:
    Display-Item:
      Item: 'DIAMOND_SWORD'
      Slot: 5
      Name: '&e&l검 대마법'
      Lore:
        - '&7대마법 부여가 가능한 장비'
        - '&a- 나무 검'
        - '&a- 돌 검'
        - '&a- 황금 검'
        - '&a- 철 검'
        - '&a- 다이아몬드 검'
    Enchantable-Items:
      - 'WOODEN_SWORD'
      - 'STONE_SWORD'
      - 'IRON_SWORD'
      - 'GOLDEN_SWORD'
      - 'DIAMOND_SWORD'
  Combat:
    Display-Item:
      Item: 'DIAMOND_SWORD'
      Slot: 10
      Name: '&e&l전투 대마법'
      Lore:
        - '&7대마법 부여가 가능한 장비'
        - '&a- 나무 검'
        - '&a- 돌 검'
        - '&a- 황금 검'
        - '&a- 철 검'
        - '&a- 다이아몬드 검'
        - '&a- 나무 도끼'
        - '&a- 돌 도끼'
        - '&a- 철 도끼'
        - '&a- 황금 도끼'
        - '&a- 다이아몬드 도끼'
    Enchantable-Items:
      - 'WOODEN_SWORD'
      - 'STONE_SWORD'
      - 'IRON_SWORD'
      - 'GOLDEN_SWORD'
      - 'DIAMOND_SWORD'      
      - 'WOODEN_AXE'
      - 'STONE_AXE'
      - 'IRON_AXE'
      - 'GOLDEN_AXE'
      - 'DIAMOND_AXE'
  Axe:
    Display-Item:
      Slot: 6
      Item: 'DIAMOND_AXE'
      Name: '&e&l도끼 대마법'
      Lore:
        - '&7대마법 부여가 가능한 장비'
        - '&a- 나무 도끼'
        - '&a- 돌 도끼'
        - '&a- 철 도끼'
        - '&a- 황금 도끼'
        - '&a- 다이아몬드 도끼'
    Enchantable-Items:
      - 'WOODEN_AXE'
      - 'STONE_AXE'
      - 'IRON_AXE'
      - 'GOLDEN_AXE'
      - 'DIAMOND_AXE'
  Hoe:
    Display-Item:
      Item: 'DIAMOND_HOE'
      Slot: 7
      Name: '&e&l괭이 대마법'
      Lore:
        - '&7대마법 부여가 가능한 장비'
        - '&a- 나무 괭이'
        - '&a- 돌 괭이'
        - '&a- 황금 괭이'
        - '&a- 철 괭이'
        - '&a- 다이아몬드 괭이'
    Enchantable-Items:
      - 'WOODEN_HOE'
      - 'STONE_HOE'
      - 'IRON_HOE'
      - 'GOLDEN_HOE'
      - 'DIAMOND_HOE'
  Pickaxe:
    Display-Item:
      Item: 'DIAMOND_PICKAXE'
      Slot: 8
      Name: '&e&l곡괭이 대마법'
      Lore:
        - '&7대마법 부여가 가능한 장비'
        - '&a- 나무 곡괭이'
        - '&a- 돌 곡괭이'
        - '&a- 황금 곡괭이'
        - '&a- 철 곡괭이'
        - '&a- 다이아몬드 곡괭이'
    Enchantable-Items:
      - 'WOODEN_PICKAXE'
      - 'STONE_PICKAXE'
      - 'IRON_PICKAXE'
      - 'GOLDEN_PICKAXE'
      - 'DIAMOND_PICKAXE'
  Tool:
    Display-Item:
      Item: 'DIAMOND_SHOVEL'
      Slot: 9
      Name: '&e&l도구 대마법'
      Lore:
        - '&7대마법 부여가 가능한 장비'
        - '&a- 모든 곡괭이'
        - '&a- 모든 도끼'
        - '&a- 모든 삽'
        - '&a- 모든 괭이'
        - '&a- 가위'
    Enchantable-Items:
      - 'WOODEN_PICKAXE'
      - 'STONE_PICKAXE'
      - 'IRON_PICKAXE'
      - 'GOLDEN_PICKAXE'
      - 'DIAMOND_PICKAXE'
      - 'WOODEN_AXE'
      - 'STONE_AXE'
      - 'IRON_AXE'
      - 'GOLDEN_AXE'
      - 'DIAMOND_AXE'
      - 'WOODEN_SHOVEL'
      - 'STONE_SHOVEL'
      - 'IRON_SHOVEL'
      - 'GOLDEN_SHOVEL'
      - 'DIAMOND_SHOVEL'
      - 'WOODEN_HOE'
      - 'STONE_HOE'
      - 'IRON_HOE'
      - 'GOLDEN_HOE'
      - 'DIAMOND_HOE'
      - 'SHEARS'
  Damaged-Items:
    Display-Item:
      Item: 'DAMAGED_ANVIL'
      Slot: 14
      Name: '&e&l내구도가 닳는 아이템 대마법'
      Lore:
        - '&7대마법 부여가 가능한 장비'
        - '&a- 낚싯대'
        - '&a- 가위'
        - '&a- 모든 도구'
        - '&a- 모든 갑옷'
        - '&a- 모든 무기'
    Enchantable-Items:
      - 'WOODEN_PICKAXE'
      - 'STONE_PICKAXE'
      - 'IRON_PICKAXE'
      - 'GOLDEN_PICKAXE'
      - 'DIAMOND_PICKAXE'
      - 'WOODEN_AXE'
      - 'STONE_AXE'
      - 'IRON_AXE'
      - 'GOLDEN_AXE'
      - 'DIAMOND_AXE'
      - 'WOODEN_SHOVEL'
      - 'STONE_SHOVEL'
      - 'IRON_SHOVEL'
      - 'GOLDEN_SHOVEL'
      - 'DIAMOND_SHOVEL'
      - 'WOODEN_HOE'
      - 'STONE_HOE'
      - 'IRON_HOE'
      - 'GOLDEN_HOE'
      - 'DIAMOND_HOE'
      - 'SHEARS'
      - 'LEATHER_HELMET'
      - 'CHAINMAIL_HELMET'
      - 'GOLDEN_HELMET'
      - 'IRON_HELMET'
      - 'DIAMOND_HELMET'
      - 'LEATHER_CHESTPLATE'
      - 'CHAINMAIL_CHESTPLATE'
      - 'GOLDEN_CHESTPLATE'
      - 'IRON_CHESTPLATE'
      - 'DIAMOND_CHESTPLATE'
      - 'LEATHER_LEGGINGS'
      - 'CHAINMAIL_LEGGINGS'
      - 'GOLDEN_LEGGINGS'
      - 'IRON_LEGGINGS'
      - 'DIAMOND_LEGGINGS'
      - 'LEATHER_BOOTS'
      - 'CHAINMAIL_BOOTS'
      - 'GOLDEN_BOOTS'
      - 'IRON_BOOTS'
      - 'DIAMOND_BOOTS'
      - 'WOODEN_SWORD'
      - 'STONE_SWORD'
      - 'IRON_SWORD'
      - 'GOLDEN_SWORD'
      - 'DIAMOND_SWORD'
      - 'BOW'
      - 'FISHING_ROD'
      - 'ELYTRA'
      - 'TRIDENT'

**Comment by badbones69** [comment]
@minejango2 https://pastebin.com/ it.

**Comment by minejango2** [comment]
https://pastebin.com/suK2Y1ag

**Comment by badbones69** [comment]
I just tested on my test server running the current dev build found on Jenkins and its working just fine with a CE book of Glowing.
![Screen Shot 2020-03-06 at 3 20 34 AM](https://user-images.githubusercontent.com/5057118/76065415-a3058f00-5f59-11ea-9b74-846222fa734f.jpg)

**Comment by minejango2** [comment]
I know, but it doesn't work. I put at my head, It doesn't give Night vision effect. 
Is it intended?
