### ISSUE TITLE
Telepahty causes items dissapear in shulker boxes.

### ISSUE THREAD

**Issue by Ainashi** [badbones69/Crazy-Enchantments#479]
Hello.
When breaking dyed shulker boxes with telepathy enchantment on item in hand, dropped shulker is empty. Telepathy is not working for default shulkers and they drop normally on the ground (but with items in them).
Also for some of my players bug persist even if they try to destroy shulkers with pickaxe without any enchantments (if they used pickaxe with Telepathy before).

This bug exist in version "v1.8 Dev Build v8".
I have tested the same on previous one ("v1.8 Dev Build v7") and Telepathy is not working for any shulker (they drop on the ground but at least items are inside).

**Comment by badbones69** [comment]
Fixed: 0ae50934711620b75e08424e189d0d2f4086be65
