### ISSUE TITLE
Events TPS Drops [Request] [Bug]

### ISSUE THREAD

**Issue by NikV2** [badbones69/Crazy-Enchantments#481]
Apparently the onPlayerMove and all the events in general cause serious TPS drops.
15+ Players all of them using Armors with Custom Enchantments causes the server's cpu - ram to go crazy.

Please try and make *everything* Async.
Perfomance should be the #1 Priority when it comes to plugins.

Yours sincirely, Nik.

**Comment by badbones69** [comment]
Thanks, this is something I have been planning as I do this with the Blast enchantment. I just have been trying to find some time to do it to basically all enchantments.

**Comment by sgdc3** [comment]
Async is NOT the correct way to handle player inventories, try to avoid checking the item lores every time, maybe store the state of the "active" enchantments for each player.

**Comment by tr7zw** [comment]
Developer of the nbt-api here, best-case you also don't check the lore in like, ever. The lore should not be used to store any data, just to hold the display data. The API is even inside the plugin [here](https://github.com/badbones69/Crazy-Enchantments/tree/v1.8/plugin/src/main/java/me/badbones69/crazyenchantments/multisupport/nbttagapi). If you need any help to modify the code parts, just reach out to me 👍

**Comment by badbones69** [comment]
@sgdc3 @tr7zw thanks for the advise guys. I’ll look into implementing something like this.
