### ISSUE TITLE
Warn Message on console log

### ISSUE THREAD

**Issue by yumjunstar** [badbones69/Crazy-Enchantments#482]
**Describe the bug**
continuos annoying warn messages are shown on console

**Versions (please complete the following information):**
 - Minecraft Server Version: [e.g. 1.8.8] Paper 1.15.2 -131
 - Plugin Version: [e.g. 1.7.9.4] CrazyEnchantments version 1.8-Dev-Build-v8.1-Build#97

*Do **NOT** say Latest use `/version crazyenchantments` in the console.

**Pastebin any errors in console**
Link: https://paste.gg/p/anonymous/4b7c67d0c1da4ad6ab406e1b47d702f8

**Issue**
Describe the issue you are having with the plugin.
Console Warn messages
**Screenshots**

![Screenshot_2020-03-18-09-39-11](https://user-images.githubusercontent.com/24960675/76916575-2f259800-6904-11ea-8252-2986a96eebae.png)

**Comment by badbones69** [comment]
Update to the newest Jenkins build to fix the error. 
https://jenkins.badbones69.com/
