### ISSUE TITLE
[Bug Report] BlockBreakEvent error

### ISSUE THREAD

**Issue by Elric02** [badbones69/Crazy-Enchantments#484]
**Describe the bug**
My console just spammed me a few seconds with this error, no idea where it comes from.

**Versions (please complete the following information):**
 - Minecraft Server Version: 1.15.2
 - Plugin Version: 1.8 Dev Build v8

**Pastebin any errors in console**
Link: https://pastebin.com/8PDmP3Kc

**Comment by badbones69** [comment]
Test the Jenkins build here and let me know if it still happens.
https://jenkins.badbones69.com/

**Comment by Elric02** [comment]
I haven't seen the error again (but maybe it came up on the console at a time I wasn't on it) so I couldn't say if it was resolved or not, sorry ^^' I'll close the topic anyway
