### ISSUE TITLE
[Bug Report] No move item

### ISSUE THREAD

**Issue by nivcoo** [badbones69/Crazy-Enchantments#485]
Hello i've probleme with v8 build, i can't move my item, the config was migrated from 1.12 to 1.15.2 so any config can create that ? thx : https://pics.edensky.fr/2020-03/19/14-58_EBj8.mp4
I try also to reset all file, with 1.15.2 clean config

**Comment by badbones69** [comment]
Test out the Jenkins build.
https://jenkins.badbones69.com/
