### ISSUE TITLE
[Bug Report] 

### ISSUE THREAD

**Issue by Issqc** [badbones69/Crazy-Enchantments#487]
**Describe the bug**
When transmog scroll is used before adding a new enchantment, the new enchantment isn't counted. Is the scroll supposed to be this and requires purchasing it again to organize the enchantment?

**Versions (please complete the following information):**
 - Minecraft Server Version: 1.15.2
 - Plugin Version: 1.8-Dev-Build-v8-RELEASE

**Comment by badbones69** [comment]
At this time yes it is required to be readded.
