### ISSUE TITLE
[Bug Report] 

### ISSUE THREAD

**Issue by Damndanl** [badbones69/Crazy-Enchantments#488]
Permissions don't work, I'm using PEX and commands only work when opped.
"You do not have permission to use that command!"

DamnDanl:
default: true
permissions:
- crazyenchantments.tinker
- crazyenchantments.blacksmith
- crazyenchantments.access

Versions:
 - Minecraft Server Version: 1.15.2
 - Plugin Version: 1.8 Dev Build v8 RELEASE

**Comment by badbones69** [comment]
What command are you running?

**Comment by Damndanl** [comment]
/ce
which only works when I'm opped

**Comment by Damndanl** [comment]
Just added that as well, I'm receiving the same message telling me I don't have enough permissions to use the command, I've set myself to the designated group with all the commands

**Comment by badbones69** [comment]
https://pastebin.com/ your perm file and send the link.
