### ISSUE TITLE
[Bug Report] BlackList Block

### ISSUE THREAD

**Issue by nivcoo** [badbones69/Crazy-Enchantments#489]
Hello, i've probleme with last version, 
I use a spawner and block stack system but when someone breaks one of these stackers with an enchant this bug, so I would like the problem to be resolved (in dev build v7 no problem) or that there have a section where we can blacklist blocks.

I also have 2 other problems with telepathy, the first one no longer counts for jobs, I have not tested with the other enchants, and the second when there is both telepathy and furnace, the furnace is not more taken into account it is the same for fortune, but the problem is telepathy.

If you want other explanation I can give some, but it's really important to fix the first bug.

MP4 of the second bug : https://pics.edensky.fr/2020-04/04/11-41_5sIx.mp4

**Comment by nivcoo** [comment]
I use latest version in jenkins website and the bugs are presents in 1.12.2 and 1.15.2

**Comment by badbones69** [comment]
Bug # 1: Could you explain a bit more for me this bug. I don't understand what's wrong.

Bug # 2: Let me know if this fixes it. bd9360187dc1ba4c7111ce8c7b9a9b03beb0f911

Bug # 3: That should be fixed in the newest Jenkins builds.

**Comment by nivcoo** [comment]
I've EpicSpawner, EpicHopper and wildstacker, when i break one of this block, stack of spawner, upgrade hopper or stack of block with wildstacker, it's bug.

And other bug with telepathy (this enchant is very bug in the last version), when my players break dark prismarine, they pickup a normal prismarine

**Comment by nivcoo** [comment]
I will take video about this 2 other bugs

**Comment by nivcoo** [comment]
Maybe this patch https://github.com/badbones69/Crazy-Enchantments/commit/bd9360187dc1ba4c7111ce8c7b9a9b03beb0f911, ptch also this other bug, i don't know

**Comment by nivcoo** [comment]
With magnet and previous build, i will try with the new build : https://pics.edensky.fr/2020-04/06/10-34_a7Dh.mp4 -> Magnet = telepathy

**Comment by nivcoo** [comment]
In last version, i've the same bug with custom spawner, custom stacker and custom hopper, in 1.8 build v7 it work correctly

**Comment by nivcoo** [comment]
Also, the jobs not work with this last build on jenkis ^^

**Comment by badbones69** [comment]
Please don't spam message.

Also, what is your Minecraft Version and CE version?

PS: Next time don't delete the template as it asked some basic questions that I need when debugging issues.

**Comment by nivcoo** [comment]
So ? Any idea ?

**Comment by badbones69** [comment]
I asked what your MC version and your CE version is.

**Comment by nivcoo** [comment]
Look my edit 8 :/

**Comment by nivcoo** [comment]
You asked me not to spam so I'm doing edit lol

**Comment by nivcoo** [comment]
So ?

**Comment by badbones69** [comment]
Let me know if the issues are fixed and if not let me know what's not working.
af6fc6cec60ffb8ff7d02cd7f69076254df162fe

**Comment by nivcoo** [comment]
https://pics.edensky.fr/2020-04/16/11-41_ZA0A.png , Why only epicspawner ? My problem is magnet not only epicspawners Oo ? So my problem is : Megnet with furnace or Auto_smelt, or magnet on stacker spawner, or stacker block, wildstack or stacker furnace, epicfurnace, so the probleme isn't only epicspawners

**Comment by badbones69** [comment]
1. For the duplicating items, I have it set to not drop any items on that event. So if its dropping items from other plugins then its probably because they didn't check if the block can drop items.
https://github.com/badbones69/Crazy-Enchantments/blob/de3db92444aa0a9370326f0aadb96448f6d424aa/plugin/src/main/java/me/badbones69/crazyenchantments/enchantments/Tools.java#L79

2. I believe this should fix the auto smelt and furnace issues. I tested and it's now working.
55f48020f20ed93a547c723cc19afcd7a47e9ed4
