### ISSUE TITLE
necromancer, infestation, guards, tamer enchants. [Bug Report] 

### ISSUE THREAD

**Issue by BrettplayMC** [badbones69/Crazy-Enchantments#491]
**Describe the bug**
Whenever someone uses the necromancer, infestation, guards or tamer enchants, they have to relog into the game after it is used to use it again (the mobs don't spawn a second time). Also an option to change the amount of mobs that spawn for each of those would be amazing (maybe a % chance?)

**Versions (please complete the following information):**
 - Minecraft Server Version: PaperSpigot 1.12.2
 - Plugin Version: 1.8-Dev-Build-v8.1-Build#114

**Issue**
This is affecting players in game.

**Comment by badbones69** [comment]
That was fixed in Build#116 
b7e1068d0ae0f5996577c76b5e0b074a1aa92518
