### ISSUE TITLE
[Request] How to increase enchantment slots

### ISSUE THREAD

**Issue by bobbyjo31** [badbones69/Crazy-Enchantments#492]
THIS IS NOT A BUG

Hello, I am wondering if there is a way for me to add something like enchantment orbs or something to increase the amount of custom enchants they can have. So it's not a universal amount. There might be a simple way I don't see if so I am sorry.

Thanks

**Comment by badbones69** [comment]
There is currently no way of adding additional slots as it's based on permission. You could give the player permission with a higher number and it should work.
