### ISSUE TITLE
[Bug Report] BOOM is not working with latests build

### ISSUE THREAD

**Issue by Futurixel** [badbones69/Crazy-Enchantments#493]
**Describe the bug**
The enchant BOOM that create an explosion with bow arrow don't work with latests builds. 

**Versions:**
 - Minecraft Server Version: 1.15.2
 - Plugin Version: CrazyEnchantments[v1.8-Dev-Build-v8.1] build 124

**Comment by badbones69** [comment]
Fixed: 05cbdfde05876fc91a6e9cf20063613bb47209d4
