### ISSUE TITLE
[Bug Report] OverLoad  problem

### ISSUE THREAD

**Issue by Futurixel** [badbones69/Crazy-Enchantments#494]
**Describe the bug:**
 When a player use enchant OverLoad and i restore health of the player with p.setHealth(p.getMaxHealth()); the additional life hearts are immediately emptied. 

**Versions:**

Minecraft Server Version: 1.15.2
Plugin Version: CrazyEnchantments[v1.8-Dev-Build-v8.1] build 124

**Comment by badbones69** [comment]
Overload uses potion effects and does not edit the player's health at all. 
You should use player attributes to set the player's health and grab the result after all modifiers are accounted for.
