### ISSUE TITLE
Change enchant chance percentage to get effect

### ISSUE THREAD

**Issue by MrFindus** [badbones69/Crazy-Enchantments#497]
I want if it possible to be able to change the percentage to get effect and the evolution per level and all other parameters.

**Comment by badbones69** [comment]
If an enchantment uses a chance system the chances can be edited. If you wish to change the chances then you need to edit here.
https://github.com/badbones69/Crazy-Enchantments/blob/81d66bc534458ee7f6e70e5e1c4e3d066fea2c06/plugin/src/main/resources/Enchantments.yml#L84

You can only change the chances and not the level of effects. If you wish to do that you will need to edit the code.
