### ISSUE TITLE
[Bug Report] Nutrition doesn't feed

### ISSUE THREAD

**Issue by Permanently** [badbones69/Crazy-Enchantments#498]
**Describe the bug**
Nutrition doesn't feed at all (weirdly though, Vampire heals?)

**Versions (please complete the following information):**
 - Minecraft Server Version: 1.12.2-R0.1-SNAPSHOT
 - Plugin Version: 1.7.9.3.8

**Pastebin any errors in console**
N/A.

**Comment by badbones69** [comment]
The v1.7 builds are no longer receiving updates so you will need to update to the v1.8 dev builds to get the fix which has already been done.
