### ISSUE TITLE
Set percentages (Question)

### ISSUE THREAD

**Issue by TommyJ100** [badbones69/Crazy-Enchantments#500]
Is there a way to make sure an enchant like headless works every time? Make it to where a head will drop if max level enchant is used rather than a lower level version of the same enchant. So far I couldn't find a way but may simply be an oversight

**Comment by badbones69** [comment]
Chance control is based on the Enchantments.yml file. These were added in v1.8 Dev Build v8 so you have to be on at least that version to use this.

https://github.com/badbones69/Crazy-Enchantments/blob/8d585ca3711636ebdaa52f8c7e7d4cc770e20a54/plugin/src/main/resources/Enchantments.yml#L1189-L1191
