### ISSUE TITLE
No enchantment assigned 

### ISSUE THREAD

**Issue by panos3500** [badbones69/Crazy-Enchantments#501]
for some reason sometimes in the common category i dont receive any enchantment and the message
"the category common has no enchantments assigned to i"

why is that happening?
[yml.zip](https://github.com/badbones69/Crazy-Enchantments/files/4524043/yml.zip)

**Comment by badbones69** [comment]
Everything seems to be working just fine on my end with those files. Are you sure you're on the most up to date version?

**Comment by panos3500** [comment]
Its working fine yes i wanted overload to have max power 0 and probably
bugged
So i disabled the overload enchant because its to broken for my server

Thanks for the response
