### ISSUE TITLE
enchantments in bedwarsREL Shop

### ISSUE THREAD

**Issue by AngelFireLA** [badbones69/Crazy-Enchantments#502]
I wanted to add the customs enchantments in my bedwarsREL shop in shop.yml but I can't find the enchantments name like SHARPNESS etc... Can someone tell me how to fix it?

**Comment by badbones69** [comment]
If you are adding enchantments to items you must add them as lore.

They must be exact color code, spelling, and spaces as it normally has on an item.

**Comment by AngelFireLA** [comment]
I know but what is the name like DAMAGE_ALL or PROTECTION_ENVIRONEMENTAL
Because I know where to put the enchantments but I don't know how

**Comment by Hitosherizu** [comment]
You would do something like "&7Blast I" to the lore. There is no "DAMAGE_ALL" style. You add them exactly as the color code, spelling, and spacing it would do if you put the book on it like Badbones said previously.
