### ISSUE TITLE
Books Dont Enchant When Dragged into Equipment

### ISSUE THREAD

**Issue by tristan1025** [badbones69/Crazy-Enchantments#503]
Minecraft 1.8-1.15

Books seem to not enchant properly when dragged over items.

In OP i can enchant them properly but without it it simply acts as if it was a normal book.
Im guessing its somthing perms related (using luck perms)

**Comment by badbones69** [comment]
Players need the Max Enchantments permission.
https://github.com/badbones69/Crazy-Enchantments/wiki/Commands-and-Permissions#options
