### ISSUE TITLE
[Bug Report] Vanilla Enchantments beyond limit

### ISSUE THREAD

**Issue by Thesense1** [badbones69/Crazy-Enchantments#504]
There is a Bug where you can put Vanilla Enchantments higher then the limit of them. People on server told me that if you have a Item with like say Sharpness 5 and 1 CE Enchanment and same on 2nd item, you can combine them through /blacks and get sharpness 6. This even works with Armor where you can put multiple protection echantments on 1 Item (Protection 4 and Blast Prot 4 as an example). Even Mending 2 is possible with this....

You can check out the stuff in the screenshots

 - Minecraft Server Version: 1.15.2
 - Plugin Version: 1.8-Dev-Build-v8.1-SNAPSHOT-Build#137

![2020-04-26_20 14 36](https://user-images.githubusercontent.com/63481007/80315903-e8786700-87fa-11ea-80cf-ae4e9dbb5463.png)
![2020-04-26_20 14 44](https://user-images.githubusercontent.com/63481007/80315904-e910fd80-87fa-11ea-96ab-48f5624b3da9.png)
![2020-04-26_20 14 53](https://user-images.githubusercontent.com/63481007/80315900-e7dfd080-87fa-11ea-97c5-e896a9dbf133.png)

**Comment by Thesense1** [comment]
Thank you for making a change to this! We found another bug in it happening with same method. You can put Mending and Infinity on 1 Bow. This shouldnt be happening since its not possible in Vanilla MC. Screenshots showing problem are attached again. For me it worked with MultiArrow and Hellforged but for others it also worked with Piercing (other bow enchants are disabled)

![2020-04-27_18 16 56_2](https://user-images.githubusercontent.com/63481007/80395745-f3430280-88b3-11ea-8b90-ceaf4aac0604.png)
![2020-04-27_18 16 57](https://user-images.githubusercontent.com/63481007/80395759-f6d68980-88b3-11ea-8b92-095b6cd304ab.png)
![2020-04-27_18 18 17](https://user-images.githubusercontent.com/63481007/80395735-f0e0a880-88b3-11ea-9546-deb21c0f5d52.png)

![2020-04-27_18 16 53](https://user-images.githubusercontent.com/63481007/80395707-e45c5000-88b3-11ea-8c0c-d5a68d130d74.png)
![2020-04-27_18 16 54](https://user-images.githubusercontent.com/63481007/80395711-e7574080-88b3-11ea-88a7-87a99e982050.png)
![2020-04-27_18 18 12](https://user-images.githubusercontent.com/63481007/80395674-da3a5180-88b3-11ea-8441-8c43a86c02ac.png)

**Comment by badbones69** [comment]
How did the bows get the enchantment in the first place? I didn't do any enchantment item checking since they are required to be the same item.

**Comment by Thesense1** [comment]
Well you can get a bow with Mending and a bow with infinity from fishing or normal enchanting/putting a enchanted book on them. Then you just need matching CE Enchantments and can put both bows together with /blacks

I’ve put them with /ce add [Enchantment] on the bow and then combined them. Other ppl on server who noticed the bug couldnt do it so they did normally.

**Comment by badbones69** [comment]
Just fixed this in the newest build.
