### ISSUE TITLE
[Bug Report] WorldGuard bypass with Telepathy

### ISSUE THREAD

**Issue by Darko266** [badbones69/Crazy-Enchantments#507]
Title says it all

My spigot version is 1.8.8
And plugin version is 1.8-Dev-Build-V8.1-SNAPSHOT-Build#139 (latest xd)

**Comment by Darko266** [comment]
Actually, without blast (only Telepathy) you can bypass WorldEdit and askyblock protection.

If you have blast and telepathy, you can mine stuff in regions

**Comment by Thesense1** [comment]
I have the same problem! Users can destroy blocks even with all permission to break or place blocks denied. This happened with Telepathy on Pickaxe. The User gets a Message from Worldguard that they cant break the block but still can break it! A other User tried it with Telepathy and Blast and it didnt work, so problem is Telepathy.

Server Version: 1.15.2
Paper Version: 245
CrazyEnchantments version: 1.8-Dev-Build-v8.1-SNAPSHOT-Build#141
