### ISSUE TITLE
perms problem

### ISSUE THREAD

**Issue by DeafKID2** [badbones69/Crazy-Enchantments#510]
i tried doing /crazyenchantments.gui
but everytime i did this pop up
![image](https://user-images.githubusercontent.com/62728956/81189001-a0222b80-8fe8-11ea-91ea-32bb8ad3e44f.png)

if there is anyone smarter then me please help :)

**Comment by winnipeg21** [comment]
the command is /ce, /crazyenchantments, /enchanter.
