### ISSUE TITLE
[Lag Report] Please Fix Auralistener

### ISSUE THREAD

**Issue by LowScarlet** [badbones69/Crazy-Enchantments#512]
**Describe the bug**
I have disabled all enchants related to Event.AuraListener, but the Auralistener still runs in my / timings report and lags when the server has 30 players on the server.

**Versions (please complete the following information):**
 - Minecraft Server Version: 1.15.2
 - Plugin Version: 1.8-Dev-Build-v8.1-SNAPSHOT-Build#140

*Do **NOT** say Latest use `/version crazyenchantments` in the console.

**Pastebin any errors in console**
Link: No Error

**Issue**
This keeps happening on my server, I can't delete this plugin because it's already a core feature of my server

**Screenshots**
https://ibb.co/mJvHGhb

**Comment by DiegoDaniel** [comment]
I having the same problem, my timings reports says that CE's AuraListener is breaking game when 20 onlines...  Hope they can fix this.

**Comment by DiegoDaniel** [comment]
I'll add my timings report if its helps.

https://timings.aikar.co/?id=40b5802f08484972942b0b96dda09f71#timings

**Comment by DiegoDaniel** [comment]
Please devs check this!!

**Comment by RyderBelserion** [comment]
This was addressed already in a PR that was merged also this is super old.
