### ISSUE TITLE
Boom not spawning tnt

### ISSUE THREAD

**Issue by Kirrasio** [badbones69/Crazy-Enchantments#514]
**Describe the bug**
Boom is not spawning tnt on bows.

**Versions (please complete the following information):**
 - Minecraft Server Version: 1.15.2 -> git-Spigot-2f5d615-d07a78b (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
 - Plugin Version: CrazyEnchantments[v1.8-Dev-Build-v8.1].jar

*Do **NOT** say Latest use `/version crazyenchantments` in the console.

**Pastebin any errors in console**
Link: no errors

**Issue**
No tnt is spawning when shooting the bow

**Screenshots**

**Comment by RyderBelserion** [comment]
They don't actually spawn TNT, They aren't meant to. They use particles and sounds to create the illusion of an explosion.
