### ISSUE TITLE
[Bug Report] 1.8.8 Console Spam

### ISSUE THREAD

**Issue by LoXR** [badbones69/Crazy-Enchantments#518]
**Describe the bug**
A few console spamming errors that appear in console.
One being this https://hastebin.com/rehudelaha.cs Or a having a way to disable Faction checks?

**Versions (please complete the following information):**
 - Minecraft Server Version: 1.8.8
 - Plugin Version: v1.8-Dev-Build-v8-RELEASE

*Do **NOT** say Latest use `/version crazyenchantments` in the console.

**Pastebin any errors in console**
Link: https://hastebin.com/rehudelaha.cs

**Issue**
Describe the issue you are having with the plugin.
COnstant spamming on crazyenchantments, on playermove, aura and a few others. All cause of possibly savagefaction compatibility no being included.

**Screenshots**

**Comment by LoXR** [comment]
Just tested v7 and no longer spams the console, just seems v8 on 1.8.8 is doing something funky.

**Comment by minejango2** [comment]
v1.7 support 1.8, but v1.8 support 1.13 or up.
