### ISSUE TITLE
Error in console [Bug Report] 

### ISSUE THREAD

**Issue by bobhenl** [badbones69/Crazy-Enchantments#529]
**Describe the bug**
Hi, one error in console has occured.

**Versions (please complete the following information):**
 - Minecraft Server Version: 1.15.2
 - Plugin Version:  v1.8 Dev Build v8

*Do **NOT** say Latest use `/version crazyenchantments` in the console.
[21:30:17 INFO]: CrazyEnchantments version 1.8-Dev-Build-v8-RELEASE
**Pastebin any errors in console**
https://pastebin.com/fXfuhS24

**Issue**
Hi, error occured... Hapened also to other plugins, like gadgetsmenu, handyorbs, nocheatplus....  https://pastebin.com/7hBzJY9n  https://pastebin.com/CcnKiN6g

**Screenshots**

**Comment by Volgeop** [comment]
?
