### ISSUE TITLE
[Bug Report] When AutoSmelt with Telepathy, gives ore one more.

### ISSUE THREAD

**Issue by minejango2** [badbones69/Crazy-Enchantments#536]
**Describe the bug**
Just like title, when AutoSmelt with Telepathy, gives ore one more.

**Versions (please complete the following information):**
 - Minecraft Server Version: [Paper 1.15.2]
 - Plugin Version: [1.8-Dev-Build-v8.1-SNAPSHOT-Build#149]

**Comment by wsman217** [comment]
Please describe the issue a bit better because I am having a hard time decrypting what one more means.
