### ISSUE TITLE
[Bug Report] Crazy enchants books are not working on netherrite

### ISSUE THREAD

**Issue by misuti** [badbones69/Crazy-Enchantments#538]
**Describe the bug**
Crazy enchants books are not working on the new netherrite tools

**Versions (please complete the following information):**
 - Minecraft Server Version: 1.16.1
 - Plugin Version: 1.8-dev-build v8.1-SNAPSHOT

**Pastebin any errors in console**
I do not have access to console

**Issue**
Drag and dropping the crazy enchants book "Haste III" with 100% success and 0% destroy rate on a netherrite pickaxe does nothing, perhaps netherrite pickaxe is yet to be added to the mod's recognized "enchantable items"

**Screenshots**

![gif](https://user-images.githubusercontent.com/26460801/87734790-3a32fb00-c806-11ea-985d-3e3ee66cbc6d.gif)

**Comment by minejango2** [comment]
You need to edit Enchantments-Type.yml. At there you need to add netherite tools at tgis file yourself

**Comment by misuti** [comment]
Thanks, I will message my server admin
