### ISSUE TITLE
Neatherite Amor and Tools 

### ISSUE THREAD

**Issue by SirDeathnote1** [badbones69/Crazy-Enchantments#540]
Hello there,

 the customs enchants doesn't apply on netherite armor and tools?

regard SirDeathnote

**Comment by minejango2** [comment]
You need to edit Enchantments-Type.yml. At there you need to add netherite tools at tgis file yourself

**Comment by SirDeathnote1** [comment]
So do i have type this - 'NETHERITE_PICKAXE
                                   - ' neatherite Pickaxe
