### ISSUE TITLE
[Bug Report] Netherite Equipments doesn't written at default Enchantment-Types.yml

### ISSUE THREAD

**Issue by minejango2** [badbones69/Crazy-Enchantments#541]
**Describe the bug**
Netherite Equipments doesn't written at default Enchantment-Types.yml.

**Versions (please complete the following information):**
 - Minecraft Server Version: [e.g. 1.16]
 - Plugin Version: [e.g. v1.8devbuild#150]

**Comment by wsman217** [comment]
This is know.
