### ISSUE TITLE
[Bug Report] Commands arent workign

### ISSUE THREAD

**Issue by kadenyaboi** [badbones69/Crazy-Enchantments#557]
**Describe the bug**
I'm on a minehut server in 1.16.3 and the plugin is installed. When I try and do any commands, it says an internal error has occurred.

**Versions (please complete the following information):**
 - Minecraft Server Version: 1.16.3
 - Plugin Version: latest one

*Do **NOT** say Latest use `/version crazyenchantments` in the console.

**Pastebin any errors in console**
Link: https://pastebin.com/

**Issue**
Won't let me do any commands

**Screenshots**

**Comment by CODEDYT** [comment]
i have the same problem on 1.16.4
