### ISSUE TITLE
Mcmmo bleeding bug, performance problem

### ISSUE THREAD

**Issue by hkkongou** [badbones69/Crazy-Enchantments#562]
**Describe the bug**

1.Big performance problem
according to timings and spark report, ce drop server performance so badly
performance problem followed by the following one

situation:
40ppl
ce enable-> tps 10
ce disable-> tps 20
i7-10700k 16GB ram only for server with aikar optimized java flag
this plugin kill server performance

2.Mcmmo bleeding bug 
https://github.com/mcMMO-Dev/mcMMO/issues/4317

**Versions (please complete the following information):**
 - Minecraft Server Version: 1.16.3 paper 253
 - Plugin Version: CrazyEnchantments[v1.8-Dev-Build-v8.1-SNAPSHOT]#154.jar

*Do **NOT** say Latest use `/version crazyenchantments` in the console.

**Pastebin any errors in console**

**Issue**
https://spark.lucko.me/#tPrEoJT5Aw
https://timings.aikar.co/?id=e1c5894d4b844a54b471fa49e484f985#plugins

**Screenshots**
![image](https://user-images.githubusercontent.com/61608872/100343898-f86b5a00-301a-11eb-8d85-ab21881c9f79.png)
![image](https://user-images.githubusercontent.com/61608872/100343908-fd300e00-301a-11eb-8a8a-f5f684fa556b.png)

**Comment by ad1tya2** [comment]
I also have the same performance issue
