### ISSUE TITLE
[Bug Report]  Huge lag caused by CrazyEnchantments::Event: m.b.c.e.Helmets (PlayerMoveEvent)

### ISSUE THREAD

**Issue by ImHumbug** [badbones69/Crazy-Enchantments#569]
Huge lag caused by CrazyEnchantments::Event: m.b.c.e.Helmets (PlayerMoveEvent)
Ver: 1.16.4
Pl Ver: CrazyEnchantments version 1.8-Dev-Build-v8.1-SNAPSHOT-Build#156
Timings: https://timings.aikar.co/?id=4fbbae59e41f4e55ab0cc8fca6fb39b9

**Comment by apatuka** [comment]
I ended removing the Helmet Listener from the Source Code, since only contains one enchantment: Commander.
