### ISSUE TITLE
[Bug Report] Spartan Anti Cheat and Blast enchantment exception

### ISSUE THREAD

**Issue by Mowstyl** [badbones69/Crazy-Enchantments#570]
**Describe the bug**
Compatibility problem with Spartan Anti Cheat and Blast enchantment.

**Versions (please complete the following information):**
 - Minecraft Server Version: Paper version git-Paper-351 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
 - Plugin Version: v1.8-Dev-Build-v8.1-SNAPSHOT-Build#158
 - Spartan Version: Spartan Build 383

**Pastebin any errors in console**
https://pastebin.com/2HL6LWJ2

**Issue**
Players get kicked by Spartan for FastBreak when using a Blast pickaxe, and the exception in the pastebin gets thrown. The blocks are not mined.

**Comment by badbones69** [comment]
Thanks working on fixing that.

**Comment by badbones69** [comment]
Replaced the old Nuker with Fast Break. This should fix this error since its been removed.
